import { escapeHTML, scriptJSON } from '../lib/security.js';
import { assets } from './templates.js';
export function page(title,config){
const dashboard=['admin','platform'].includes(config.mode);
const symbol='<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M3 21V4h18v17M3 7h18M7 7v14M12 7v14M17 7v14M2 21h20"/></svg>';
return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHTML(title)} — PortonSmart</title><link rel="stylesheet" href="${assets.legacyStyle}"></head><body class="${dashboard?'dashboard'+(config.mode==='platform'?' platform':config.mode==='admin'&&config.user?.role!=='master'?' resident':''):'entry'}">
${dashboard?`<aside class="sidebar" id="sidebar"><div class="sidebar-brand">${symbol}<span>PortonSmart</span></div><div class="nav-caption">${config.mode==='platform'?'Plataforma':config.user?.role==='master'?'Administración':'Mi acceso'}</div><nav id="nav" aria-label="Menú principal"></nav><div class="sidebar-foot">Gestión de accesos</div></aside><button class="menu-overlay" id="menu-overlay" aria-label="Cerrar menú"></button>`:''}
<div class="shell">${dashboard?`<header class="topbar"><button class="mobile-toggle" id="menu-toggle" aria-label="Abrir menú" aria-expanded="false" aria-controls="sidebar"><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><div class="topbar-title"><h1>${escapeHTML(title)}</h1><p class="breadcrumb" id="view-label">Panel de administración</p></div><div class="user-badge"><div class="user-info">${escapeHTML(config.user?.username||'')}<small>${config.mode==='platform'?'Plataforma':config.user?.role==='master'?'Administrador':'Usuario'}</small></div><div class="avatar">${escapeHTML((config.user?.username||'A').slice(0,1).toUpperCase())}</div></div></header>`:''}<main>${dashboard?'':`<div class="entry-brand">${symbol}<span>PortonSmart</span></div><p class="entry-building">${escapeHTML(title)}</p><nav id="nav"></nav>`}<div id="notice" class="message" role="status" aria-live="polite"></div><div id="view"></div></main></div><script type="application/json" id="app-config">${scriptJSON(config)}</script><script defer src="${assets.legacy}"></script></body></html>`;
}
