import {readFileSync,writeFileSync,mkdirSync,readdirSync,unlinkSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve,relative} from 'node:path';
import {createRequire} from 'node:module';
import {build} from 'esbuild';
const require=createRequire(import.meta.url),postcss=require('postcss'),tailwind=require('tailwindcss');
const root=fileURLToPath(new URL('.',import.meta.url));process.chdir(root);mkdirSync('dist/assets',{recursive:true});
const css=await postcss([tailwind(require('./tailwind.config.cjs'))]).process(readFileSync('src/styles.css','utf8'),{from:resolve('src/styles.css')});writeFileSync('src/compiled.css',css.css);
const {design}=await import('./legacy/design.js');writeFileSync('legacy/compiled.css',"@import '@fontsource/roboto/latin-400.css';\n@import '@fontsource/roboto/latin-500.css';\n@import '@fontsource/roboto/latin-700.css';\n"+readFileSync('legacy/base.css','utf8')+design);
const output=await build({absWorkingDir:root,entryPoints:{app:'src/app.js',style:'src/compiled.css',legacy:'legacy/index.js',legacyStyle:'legacy/compiled.css'},bundle:true,minify:true,metafile:true,outdir:'dist/assets',entryNames:'[name]-[hash]',assetNames:'[name]-[hash]',loader:{'.woff2':'file','.woff':'file','.ttf':'file'},target:'es2022'});
const fresh=new Set(Object.keys(output.metafile.outputs).map(p=>p.split('/').pop()));for(const name of readdirSync('dist/assets'))if(!fresh.has(name))unlinkSync(resolve('dist/assets',name));
const assets={};for(const [path,data] of Object.entries(output.metafile.outputs))if(data.entryPoint)assets[data.entryPoint.endsWith('app.js')?'app':data.entryPoint.endsWith('index.js')?'legacy':data.entryPoint.startsWith('legacy/')?'legacyStyle':'style']='/assets/'+path.split('/').pop();
const templates=Object.fromEntries(['admin','resident'].map(name=>[name,readFileSync('templates/'+name+'.html','utf8')]));
writeFileSync('../src/html/templates.js','// Generated from frontend/templates.\nexport const templates='+JSON.stringify(templates)+';\nexport const assets='+JSON.stringify(assets)+';\n');
writeFileSync('dist/_headers','/assets/*\n  Cache-Control: public, max-age=31536000, immutable\n  X-Content-Type-Options: nosniff\n');
console.log('Frontend compilado: '+Object.keys(output.metafile.outputs).length+' archivos estáticos.');
