import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdirSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {makeDB} from './db.mjs';
import * as db from '../src/lib/db.js';
import {hashSecret} from '../src/lib/security.js';
const {default:worker}=await import(process.env.WORKER_BUNDLE?pathToFileURL(resolve(process.env.WORKER_BUNDLE)).href:new URL('../src/index.js',import.meta.url).href);
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PATH||'playwright');
const {sqlite,db:DB}=makeDB(),env={DB,ADMIN_SIGNING_SECRET:'test-only-signing-key-with-at-least-32-chars'};
const tenantId=await db.createTenant(env,{slug:'aurora',name:'Residencial Aurora',gateName:'Portón principal',triggerUrl:'https://device.test/main',masterUsername:'admin',masterSecret:'password-test'});
const gate=sqlite.prepare('SELECT * FROM gates').get();
const parking=await db.saveGate(env,tenantId,{name:'Estacionamiento',triggerUrl:'https://device.test/parking'});
await db.createUser(env,tenantId,{username:'pablo',secret:'password-test',gateIds:[gate.id,parking]});
const user=sqlite.prepare("SELECT * FROM users WHERE username='pablo'").get();
await db.createCode(env,user,{gateId:gate.id,label:'Visita de María',expiresAt:Date.now()+2*3600000,singleUse:false,visit:true});
await db.createCode(env,user,{gateId:parking,label:'Entrega de supermercado',expiresAt:Date.now()+30*60000,singleUse:false});
const secret=await hashSecret('password-test');sqlite.prepare('INSERT INTO platform_admins(id,username,secret,created_at) VALUES(?,?,?,?)').run('platform','platform',secret,1);
for(let i=0;i<30;i++)sqlite.prepare('INSERT INTO logs(id,tenant_id,gate_id,gate_name,owner_id,owner,label,outcome,at) VALUES(?,?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),tenantId,gate.id,gate.name,user.id,user.username,i===0?'=HYPERLINK("test")':'Visita',i%7===0?'not_sent':'sent',Date.now()-i*2300000);
let commands=[];globalThis.fetch=async url=>{commands.push(String(url));return new Response('ok');};
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
const output=resolve('work/portonsmart-preview');mkdirSync(output,{recursive:true});
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('https://app.test/**',async route=>{const r=route.request(),response=await worker.fetch(new Request(r.url(),{method:r.method(),headers:r.headers(),...(r.postData()?{body:r.postData()}:{})}),env,{waitUntil:p=>p});await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:await response.text()});});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 async function login(username){await page.goto('https://app.test/t/aurora?access=resident');await page.getByLabel('Usuario',{exact:true}).fill(username);await page.getByLabel('Contraseña',{exact:true}).fill('password-test');await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.waitForURL('**/admin');await page.getByRole('heading',{name:'Códigos de acceso'}).waitFor();}
 const shot=async name=>{await page.screenshot({path:resolve(output,name+'.png'),fullPage:true,animations:'disabled'});};
 await login('admin');assert.equal(commands.length,0);await shot('administrador');
 await login('pablo');await page.locator('.pass-card').first().waitFor();await shot('residente');assert.equal(await page.locator('.pass-card').count(),2);
 const main=page.locator('.gate-card').filter({hasText:'Portón principal'}),hold=main.locator('.hold-button'),box=await hold.boundingBox();
 await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.waitForTimeout(100);await page.mouse.up();await page.waitForTimeout(650);assert.equal(commands.length,0,'short touch must not send');
 await page.mouse.down();await page.mouse.move(0,0);await page.waitForTimeout(650);await page.mouse.up();assert.equal(commands.length,0,'leaving button cancels hold');
 await hold.focus();await page.keyboard.down('Space');await page.waitForTimeout(750);await page.keyboard.up('Space');await main.getByText('Orden de apertura enviada a Portón principal',{exact:true}).waitFor();assert.deepEqual(commands,['https://device.test/main']);await page.waitForTimeout(650);assert.equal(commands.length,1,'one hold sends once');
 await page.locator('.gate-card').filter({hasText:'Estacionamiento'}).getByRole('button',{name:'Abrir con confirmación'}).click();await page.getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(commands.length,1,'cancel does not send');
 await page.locator('.gate-card').filter({hasText:'Estacionamiento'}).getByRole('button',{name:'Abrir con confirmación'}).click();await page.getByRole('dialog').getByRole('button',{name:'Enviar orden',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});assert.equal(commands.at(-1),'https://device.test/parking');
 await page.locator('#nav').getByRole('button',{name:'Historial',exact:true}).click();await page.getByLabel('Buscar en historial').fill('=HYPERLINK');assert.equal(await page.locator('tbody tr').count(),1);const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar CSV'}).click();const csv=readFileSync(await (await downloaded).path(),'utf8');assert.ok(csv.includes("'=HYPERLINK"),'CSV must escape spreadsheet formulas');await shot('historial');
 await page.setViewportSize({width:390,height:844});await page.locator('.mobile-tabs').getByRole('button',{name:'Accesos',exact:true}).click();await page.getByRole('heading',{name:'Mis accesos',exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('residente-movil');
 await page.locator('.mobile-tabs').getByRole('button',{name:'Pases',exact:true}).click();await page.locator('.pass-card').first().waitFor();await page.getByRole('button',{name:'Invitar a alguien',exact:true}).click();await page.getByRole('dialog').getByLabel('Portón',{exact:true}).selectOption(gate.id);await page.getByLabel('Nombre o nota').fill('Servicio de prueba');await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByLabel('Tipo',{exact:true}).selectOption('repeat');await page.getByLabel('El acceso vence').selectOption('30');await shot('nuevo-pase-movil');await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.getByRole('button',{name:'Crear código',exact:true}).click();await page.getByRole('heading',{name:'Compartir acceso'}).waitFor();const saved=sqlite.prepare("SELECT * FROM codes WHERE label='Servicio de prueba'").get();assert.ok(saved.expires_at>Date.now()+29*60000&&saved.expires_at<=Date.now()+30*60000);await page.getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.goto('https://app.test/t/aurora');await shot('visitante-movil');assert.equal(commands.length,2);
 await page.goto('https://app.test/platform');await page.getByLabel('Usuario',{exact:true}).fill('platform');await page.getByLabel('Contraseña',{exact:true}).fill('password-test');await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.waitForURL('**/platform/admin');await page.getByRole('heading',{name:'Edificios',exact:true}).waitFor();await page.setViewportSize({width:1440,height:1000});await shot('superadministrador');
 assert.deepEqual(errors,[]);console.log('OK PortonSmart: resumen, residente, móvil, pulsación/cancelación, destino, CSV y vigencias.');
}finally{await browser.close();}
