import test from 'node:test';
import assert from 'node:assert/strict';
import {makeDB} from './db.mjs';
import * as db from '../src/lib/db.js';
import {createPass,listPasses,extendPass,visitorGates} from '../src/lib/passes.js';
async function setup(){const {sqlite,db:DB}=makeDB(),env={DB};const tenant=await db.createTenant(env,{slug:'alpha',name:'Alpha',gateName:'Uno',triggerUrl:'https://device.test/one',masterUsername:'admin',masterSecret:'test-password'}),g1=sqlite.prepare('SELECT id FROM gates').get().id,g2=await db.saveGate(env,tenant,{name:'Dos',triggerUrl:'https://device.test/two'});await db.createUser(env,tenant,{username:'resident',secret:'test-password',gateIds:[g1,g2]});const user=sqlite.prepare("SELECT * FROM users WHERE username='resident'").get();return {sqlite,env,user,tenant,g1,g2};}
test('pase multiacceso: selección autorizada, reserva compartida y revocación al quitar permiso secundario',async()=>{const {sqlite,env,user,tenant,g1,g2}=await setup();const {code}=await createPass(env,user,{label:'Entrega',category:'Entrega',minutes:120,gateIds:[g1,g2]});assert.equal((await listPasses(env,user))[0].access.length,2);assert.equal((await visitorGates(env,tenant,code)).length,2);assert.equal(await db.claimCode(env,tenant,code,'ajeno'),null);const row=await db.claimCode(env,tenant,code,g2);assert.equal(row.gate_id,g2);assert.equal(await db.claimCode(env,tenant,code,g1),null);await db.finishCode(env,row,await db.getGate(env,tenant,g2),'sent');await db.setPermissions(env,tenant,user.id,[g1]);assert.equal(sqlite.prepare('SELECT status FROM codes WHERE code=?').get(code).status,'revoked');assert.equal(await db.claimCode(env,tenant,code,g1),null);});
test('cambiar la integración secundaria revoca todo el pase; creación parcial revierte',async()=>{const {sqlite,env,user,tenant,g1,g2}=await setup();const {code}=await createPass(env,user,{label:'Visita',minutes:30,gateIds:[g1,g2]});await db.saveGate(env,tenant,{gateId:g2,name:'Dos',triggerUrl:'https://device.test/replaced'});assert.equal(await db.claimCode(env,tenant,code,g2),null);assert.equal(await db.claimCode(env,tenant,code,g1),null);sqlite.exec("CREATE TRIGGER reject_pass BEFORE INSERT ON code_gates WHEN NEW.gate_id='"+g2+"' BEGIN SELECT RAISE(ABORT,'test failure'); END");const before=sqlite.prepare('SELECT COUNT(*) n FROM codes').get().n;await assert.rejects(createPass(env,user,{label:'Fail',minutes:30,gateIds:[g1,g2]}));assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM codes').get().n,before);});
test('extensión: vence pronto, dueño, no visita, no duplicación y no resucita revocados',async()=>{const {sqlite,env,user,g1}=await setup();const {code}=await createPass(env,user,{label:'Servicio',minutes:30,gateIds:[g1]});const expires=Date.now()+300000;sqlite.prepare('UPDATE codes SET expires_at=? WHERE code=?').run(expires,code);await assert.rejects(extendPass(env,{...user,id:'another'},{code,expiresAt:expires}));await extendPass(env,user,{code,expiresAt:expires});await assert.rejects(extendPass(env,user,{code,expiresAt:expires}));assert.equal(sqlite.prepare('SELECT expires_at FROM codes WHERE code=?').get(code).expires_at,expires+1800000);sqlite.prepare("UPDATE codes SET status='revoked',expires_at=? WHERE code=?").run(expires,code);await assert.rejects(extendPass(env,user,{code,expiresAt:expires}));sqlite.prepare("UPDATE codes SET status='active',visit_mode=1 WHERE code=?").run(code);await assert.rejects(extendPass(env,user,{code,expiresAt:expires}));});
test('visita multiacceso comparte los mismos diez minutos entre portones',async()=>{const {sqlite,env,user,tenant,g1,g2}=await setup();const {code}=await createPass(env,user,{label:'Visita',mode:'visit',minutes:30,gateIds:[g1,g2]});const a=await db.claimCode(env,tenant,code,g1);await db.finishCode(env,a,await db.getGate(env,tenant,g1),'sent');const deadline=sqlite.prepare('SELECT expires_at FROM codes WHERE code=?').get(code).expires_at;const b=await db.claimCode(env,tenant,code,g2);await db.finishCode(env,b,await db.getGate(env,tenant,g2),'sent');assert.equal(sqlite.prepare('SELECT expires_at FROM codes WHERE code=?').get(code).expires_at,deadline);});

test('fecha personalizada conserva el límite y rechaza fechas pasadas o fuera de rango',async()=>{const {sqlite,env,user,g1}=await setup();const expiresAt=Date.now()+3*86400000;const {code}=await createPass(env,user,{label:'Programada',mode:'visit',expiresAt,gateIds:[g1]});const row=sqlite.prepare('SELECT expires_at,visit_mode FROM codes WHERE code=?').get(code);assert.equal(row.expires_at,expiresAt);assert.equal(row.visit_mode,1);for(const invalid of [Date.now()-1000,Date.now()+3651*86400000,'mañana'])await assert.rejects(createPass(env,user,{label:'Inválida',mode:'visit',expiresAt:invalid,gateIds:[g1]}));});
