import {readFileSync} from 'node:fs';
import {offlineMQTT} from './fake-mqtt.mjs';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { makeDB } from './db.mjs';
import { hashSecret } from '../src/lib/security.js';
import * as db from '../src/lib/db.js';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
const {default:worker}=await import(process.env.WORKER_BUNDLE?pathToFileURL(resolve(process.env.WORKER_BUNDLE)).href:new URL('../src/index.js',import.meta.url).href);
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {sqlite,db:DB,migrate}=makeDB();migrate();
const env={DB,ADMIN_SIGNING_SECRET:'test-only-signing-key-with-at-least-32-chars',MQTT_ENCRYPTION_KEY:Buffer.alloc(32,12).toString('base64')};
const secret=await hashSecret('password-test');
sqlite.prepare('INSERT INTO platform_admins(id,username,secret,created_at) VALUES(?,?,?,?)').run('pa','platform',secret,1);
const tenantId=await db.createTenant(env,{slug:'alpha',name:'Edificio Alpha',gateName:'Principal',triggerUrl:'https://device.test/one',masterUsername:'admin',masterSecret:'password-test'});
const g2=await db.saveGate(env,tenantId,{name:'Trasero <img src=x onerror=alert(1)>',triggerUrl:'https://device.test/two'});
await db.createTenant(env,{slug:'beta',name:'Edificio Beta',gateName:'Beta puerta',triggerUrl:'https://device.test/beta',masterUsername:'admin',masterSecret:'password-test'});
let opened=[];
globalThis.fetch=async url=>{opened.push(url);return new Response('ok');};
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
try{
 const context=await browser.newContext();
 await context.route('https://app.test/**',async route=>{const r=route.request();if(new URL(r.url()).pathname.startsWith('/assets/')){const file=new URL('../frontend/dist'+new URL(r.url()).pathname,import.meta.url);await route.fulfill({status:200,contentType:String(file).endsWith('.css')?'text/css':String(file).endsWith('.js')?'text/javascript':'font/woff2',body:readFileSync(file)});return;}const res=await worker.fetch(new Request(r.url(),{method:r.method(),headers:r.headers(),...(r.postData()?{body:r.postData()}:{})}),env,{waitUntil:p=>p});await route.fulfill({status:res.status,headers:Object.fromEntries(res.headers),body:await res.text()});});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto('https://app.test/t/alpha');await page.getByRole('button',{name:'Entrar con mi usuario',exact:true}).click();await page.getByLabel('Usuario',{exact:true}).fill('admin');await page.getByLabel('Contraseña',{exact:true}).fill('wrong-password');await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.getByRole('alert').filter({hasText:'Usuario o contraseña incorrectos'}).waitFor();assert.ok(await page.getByRole('alert').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}));await page.getByLabel('Contraseña',{exact:true}).fill('password-test');await page.getByRole('button',{name:'Entrar',exact:true}).click();
 await page.waitForURL('**/admin');await page.goto('https://app.test/t/alpha/admin?view=codes');await page.getByRole('heading',{name:'Códigos de acceso'}).waitFor();
 await page.getByRole('button',{name:'Invitar a alguien',exact:true}).click();
 await page.getByRole('dialog').getByLabel('Portón',{exact:true}).selectOption(g2);
 await page.getByRole('dialog').getByLabel('Nombre o nota').fill('Visita de prueba');
 await page.getByRole('dialog').getByRole('button',{name:'Siguiente',exact:true}).click();
 await page.getByRole('dialog').getByLabel('Tipo',{exact:true}).selectOption('unlimited');assert.equal(await page.getByLabel('Puede comenzar hasta').isVisible(),false);
 await page.getByRole('dialog').getByRole('button',{name:'Siguiente',exact:true}).click();
 assert.ok((await page.locator('.wizard-summary').textContent()).includes('Trasero'));
 await page.getByRole('dialog').getByRole('button',{name:'Crear código',exact:true}).click();
 await page.getByRole('heading',{name:'Compartir acceso'}).waitFor();
 assert.ok((await page.getByRole('dialog').textContent()).includes('Edificio Alpha'));
 assert.ok((await page.getByRole('dialog').textContent()).includes('Trasero <img'));
 assert.equal(await page.locator('img').count(),0);
 const saved=sqlite.prepare('SELECT * FROM codes').get();assert.equal(saved.expires_at,null);const code=saved.code;
 await page.getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.getByRole('button',{name:'Abrir portón',exact:true}).click();
 await page.getByRole('dialog').getByLabel('Portón',{exact:true}).selectOption(g2);
 await page.getByRole('button',{name:'Enviar orden',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});
 assert.deepEqual(opened,['https://device.test/two']);
 await page.getByRole('button',{name:'Historial',exact:true}).click();await page.getByRole('heading',{name:'Historial de órdenes'}).waitFor();
 assert.ok((await page.locator('table').textContent()).includes('Trasero <img'));
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.getByRole('button',{name:'Abrir menú',exact:true}).click();
 await page.getByRole('button',{name:'Portones',exact:true}).click();
 await page.getByRole('heading',{name:'Mis portones autorizados'}).waitFor();
 assert.equal(await page.locator('body.menu-open').count(),0);
 await page.goto('https://app.test/t/alpha/?code='+code);await page.getByRole('button',{name:'Enviar orden de apertura'}).click();
 await page.getByRole('button',{name:'Orden confirmada',exact:true}).waitFor();
 assert.equal(opened.at(-1),'https://device.test/two');assert.equal(await page.locator('.opening-result.success .gate-badge').count(),0);assert.equal(await page.locator('.visitor-open[data-state=confirmed] .gate-opening .gate-left').count(),1);await page.locator('.gate-opening').evaluate(async e=>{await Promise.all(e.getAnimations({subtree:true}).map(a=>a.finished));});assert.ok(await page.locator('.gate-opening .gate-left').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41<0));assert.ok(await page.locator('.gate-opening .gate-right').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41>0));await page.screenshot({path:'work/ui-update/visitor-success.png',fullPage:true});
 await page.goto('https://app.test/platform');await page.getByLabel('Usuario',{exact:true}).fill('platform');await page.getByLabel('Contraseña',{exact:true}).fill('password-test');await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.waitForURL('**/platform/admin');await page.goto('https://app.test/platform/admin?view=legacy');
 await page.getByRole('heading',{name:'Edificios',exact:true}).waitFor();
 await page.getByRole('row').filter({hasText:'Edificio Alpha'}).getByRole('button',{name:'Administrar'}).click();
 await page.getByRole('heading',{name:'Portones registrados'}).waitFor();
 await page.getByRole('row').filter({hasText:'Principal'}).getByRole('button',{name:'Editar',exact:true}).click();
 await page.getByRole('dialog').getByLabel('Nombre',{exact:true}).fill('Principal actualizado');await page.getByRole('dialog').getByRole('button',{name:'Guardar'}).click();
 await page.getByRole('dialog').waitFor({state:'detached'});
 assert.equal(sqlite.prepare("SELECT name FROM gates WHERE tenant_id=? AND name='Principal actualizado'").get(tenantId).name,'Principal actualizado');
 await page.getByRole('button',{name:'Volver a edificios'}).click();
 await page.getByRole('row').filter({hasText:'Edificio Beta'}).getByRole('button',{name:'Administrar'}).click();await page.getByRole('heading',{name:'Usuarios de Edificio Beta'}).waitFor();
 assert.equal(await page.getByRole('heading',{name:'Usuarios de Edificio Alpha'}).count(),0);
 assert.equal(sqlite.prepare("SELECT COUNT(*) AS n FROM gates WHERE name='Beta puerta'").get().n,1);
 await page.setViewportSize({width:1280,height:900});
 const u=sqlite.prepare("SELECT * FROM users WHERE tenant_id=? AND role='master'").get(tenantId),g=sqlite.prepare('SELECT * FROM gates WHERE tenant_id=? ORDER BY created_at').get(tenantId);
 sqlite.prepare("INSERT INTO codes(code,tenant_id,gate_id,owner_id,owner,label,created_at) VALUES('001234',?,?,?,?,?,1)").run(tenantId,g.id,u.id,u.username,'Antiguo');
 for(let i=0;i<101;i++)sqlite.prepare("INSERT INTO codes(code,tenant_id,gate_id,owner_id,created_at,status) VALUES(?,?,?,?,?,'revoked')").run('ui-'+i,tenantId,g.id,u.id,Date.now()+i);
 await page.goto('https://app.test/t/alpha/admin?view=codes');await page.getByRole('heading',{name:'Códigos de acceso'}).waitFor();
 await page.getByLabel('Estado del código').selectOption('');await page.getByRole('button',{name:'Buscar',exact:true}).click();await page.getByRole('button',{name:'Página siguiente',exact:true}).click();await page.getByText('Página 2 ·',{exact:false}).waitFor();
 await page.getByLabel('Buscar código exacto').fill('001234');await page.getByRole('button',{name:'Buscar',exact:true}).click();await page.getByRole('row').filter({hasText:'Antiguo'}).waitFor();
 assert.equal(await page.locator('[data-code-list] tbody tr').count(),1);
 await page.goto('https://app.test/platform/admin?view=legacy');await page.getByRole('button',{name:'Cambiar mi contraseña',exact:true}).click();await page.getByRole('dialog').getByLabel('Contraseña actual',{exact:true}).waitFor();await page.getByRole('button',{name:'Cancelar',exact:true}).click();
 await page.goto('https://app.test/t/alpha/admin?view=codes');await page.getByRole('button',{name:'Usuarios',exact:true}).click();await page.getByRole('button',{name:'Agregar usuario',exact:true}).click();await page.getByRole('dialog').getByLabel('Usuario',{exact:true}).fill('new-neighbor');await page.getByRole('dialog').getByLabel('Contraseña (mínimo 8 caracteres)').fill('neighbor-password');await page.getByRole('dialog').getByLabel('Principal actualizado',{exact:true}).check();await page.getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('heading',{name:'Usuario creado',exact:true}).waitFor();const share=await page.getByRole('link',{name:'Compartir bienvenida por WhatsApp'}).getAttribute('href');const welcome=new URL(share).searchParams.get('text');assert.ok(welcome.includes('new-neighbor')&&welcome.includes('Principal actualizado')&&welcome.includes('access=resident'));await page.screenshot({path:'work/ui-update/welcome.png',fullPage:true});await page.getByRole('button',{name:'Cerrar',exact:true}).click();await page.getByRole('row').filter({hasText:'new-neighbor'}).getByRole('button',{name:'Compartir',exact:true}).click();await page.getByRole('heading',{name:'Compartir acceso de new-neighbor'}).waitFor();const existingText=new URL(await page.getByRole('link',{name:'Compartir bienvenida por WhatsApp'}).getAttribute('href')).searchParams.get('text');assert.ok(existingText.includes('Usa la contraseña que recibiste'));assert.ok(!existingText.includes('neighbor-password'));await page.getByRole('button',{name:'Cerrar',exact:true}).click();await page.goto('https://app.test/t/alpha?access=resident');await page.getByLabel('Usuario',{exact:true}).waitFor();assert.equal(await page.getByLabel('Código de seis dígitos').isVisible(),false);const visit=await db.createCode(env,u,{gateId:g.id,label:'Visita 10 minutos',days:1,singleUse:false,visit:true});await page.goto('https://app.test/t/alpha?code='+visit.code);const before=opened.length;await page.getByRole('button',{name:'Enviar orden de apertura',exact:true}).click();await page.getByRole('heading',{name:'Una visita · 10 minutos',exact:true}).waitFor();assert.equal(opened.length,before);await page.getByRole('button',{name:'Estoy frente al portón, abrir',exact:true}).click();await page.getByText('Puedes volver a abrir durante',{exact:false}).waitFor();assert.equal(opened.length,before+1);await page.reload();await page.getByText('Puedes volver a abrir durante',{exact:false}).waitFor();assert.equal(opened.length,before+1);await page.getByRole('button',{name:'Necesito ayuda',exact:true}).click();await page.getByRole('heading',{name:'Ayuda para entrar'}).waitFor();await page.getByRole('button',{name:'Entendido',exact:true}).click();await page.screenshot({path:'work/ui-update/recovered-visit.png',fullPage:true});assert.deepEqual(errors,[]);
 await page.goto('https://app.test/platform/admin?view=legacy');assert.equal(await page.getByRole('button',{name:'Conexión de relés',exact:true}).count(),0);await page.getByRole('button',{name:'Configuración',exact:true}).click();await page.getByRole('button',{name:'Editar conexión MQTT',exact:true}).click();
 await page.getByLabel('Contraseña de envío',{exact:true}).fill('ui-mqtt-command-secret');await page.getByLabel('Contraseña de consulta',{exact:true}).fill('ui-mqtt-read-secret');await page.getByLabel('Tu contraseña de plataforma para confirmar',{exact:true}).fill('password-test');
 await page.getByRole('dialog').getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});
 await page.getByRole('button',{name:'Editar conexión MQTT',exact:true}).click();assert.equal(await page.getByLabel('Contraseña de envío',{exact:true}).inputValue(),'');assert.equal(await page.getByLabel('Contraseña de consulta',{exact:true}).inputValue(),'');await page.screenshot({path:'work/ui-update/mqtt-settings.png',fullPage:true});await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();
 assert.ok(!sqlite.prepare('SELECT payload FROM relay_settings').get().payload.includes('ui-mqtt-command-secret'));
 assert.equal(await page.getByRole('heading',{name:'Inventario de relés',exact:true}).count(),1);
 await page.getByRole('button',{name:'Registrar relé',exact:true}).click();await page.getByLabel('Nombre del relé',{exact:true}).fill('Relé de prueba');await page.getByLabel('Identificador del relé',{exact:true}).fill('test-ui-device');await page.getByRole('dialog').getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});
 globalThis.fetch=async url=>{assert.ok(String(url).includes('.hivemq.cloud:8884/mqtt'));return offlineMQTT('test-ui-device');};
 await page.getByRole('row').filter({hasText:'test-ui-device'}).getByRole('button',{name:'Comprobar conexión',exact:true}).click();await page.getByRole('dialog').getByText('Desconectado',{exact:true}).waitFor();await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await page.getByRole('row').filter({hasText:'test-ui-device'}).getByText('Desconectado',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'work/ui-update/relay-inventory-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1280,height:900});
 await page.getByRole('button',{name:'Edificios',exact:true}).click();await page.getByRole('row').filter({hasText:'Edificio Alpha'}).getByRole('button',{name:'Administrar',exact:true}).click();await page.getByRole('button',{name:'Agregar portón',exact:true}).click();
 await page.getByRole('dialog').getByLabel('Nombre',{exact:true}).fill('Relé de prueba');await page.getByLabel('Relé del inventario',{exact:true}).selectOption('test-ui-device');assert.equal(await page.getByLabel('URL de activación HTTPS',{exact:true}).isVisible(),false);
 await page.getByRole('dialog').getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});await page.getByRole('row').filter({hasText:'test-ui-device'}).getByRole('button',{name:'Comprobar conexión'}).waitFor();await page.screenshot({path:'work/ui-update/mqtt-assignment.png',fullPage:true});
 const relayRow=page.getByRole('row').filter({hasText:'test-ui-device'});await relayRow.getByText('Habilitado',{exact:true}).waitFor();await relayRow.getByText('Desconectado',{exact:true}).waitFor();await relayRow.getByRole('button',{name:'Comprobar conexión',exact:true}).click();await page.getByRole('dialog').getByText('Desconectado',{exact:true}).waitFor();await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await relayRow.getByText('Desconectado',{exact:true}).waitFor();
 await page.reload();await page.getByRole('row').filter({hasText:'Edificio Alpha'}).getByRole('button',{name:'Administrar',exact:true}).click();await page.getByRole('row').filter({hasText:'test-ui-device'}).getByText('Desconectado',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Agregar portón',exact:true}).click();assert.equal(await page.getByLabel('Relé del inventario',{exact:true}).locator('option[value="test-ui-device"]').count(),0);await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();assert.deepEqual(errors,[]);
 await page.getByRole('button',{name:'Edificios',exact:true}).click();
 for(let i=0;i<3;i++){
  await page.getByRole('button',{name:'Crear edificio',exact:true}).click();const form=page.getByRole('dialog');await form.getByLabel('Nombre',{exact:true}).fill('Torre Álamos');
  assert.equal(await form.getByLabel('Enlace personalizado',{exact:true}).isVisible(),false);await form.getByText('Vista previa: https://app.test/t/torre-alamos',{exact:true}).waitFor();
  if(i!==1){await form.getByRole('button',{name:'Personalizar enlace',exact:true}).click();await form.getByLabel('Enlace personalizado',{exact:true}).fill('mi-enlace');await form.getByLabel('Nombre',{exact:true}).fill('Torre Renombrada');await form.getByText('Vista previa: https://app.test/t/mi-enlace',{exact:true}).waitFor();
    if(i===0){await form.getByRole('button',{name:'Usar enlace automático',exact:true}).click();await form.getByText('Vista previa: https://app.test/t/torre-renombrada',{exact:true}).waitFor();await form.getByLabel('Nombre',{exact:true}).fill('Torre Álamos');}
  }
  await form.getByLabel('Nombre del primer portón',{exact:true}).fill('Principal');await form.getByLabel('Cómo se controla',{exact:true}).selectOption('demo');await form.getByLabel('Usuario administrador',{exact:true}).fill('admin');await form.getByLabel('Contraseña del administrador',{exact:true}).fill('test-new-building');
  if(i===0)await page.screenshot({path:'work/ui-update/automatic-building-link.png',fullPage:true});
  await form.getByRole('button',{name:'Guardar',exact:true}).click();await form.waitFor({state:'detached'});const expected=i===0?'torre-alamos':i===1?'torre-alamos-2':'mi-enlace';await page.getByText('Edificio creado. Enlace: https://app.test/t/'+expected,{exact:true}).waitFor();assert.ok(sqlite.prepare('SELECT id FROM tenants WHERE slug=?').get(expected));
 }
 assert.deepEqual(errors,[]);console.log('OK UI: flujos existentes, inventario, estado offline y enlaces automáticos, personalizados y duplicados.');
}finally{await browser.close();}
