// Shared browser UI. All database content uses textContent; each action captures its own building ID.
export function clientApp(config){
  const $=id=>document.getElementById(id),view=$('view'),nav=$('nav'),notice=$('notice');
  const platform=config.mode==='platform',base=platform?'/platform':'/t/'+(config.tenant?.slug||'');
  let revision=0;const codeFilters=new Map();
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  function feedback(target,text,error=false){target.textContent=text;target.className='message '+(error?'error':'success');target.setAttribute('role',error?'alert':'status');if(text){target.tabIndex=-1;target.focus({preventScroll:true});target.scrollIntoView({block:'center',behavior:'instant'});}}
  const message=(text,error=false)=>feedback(notice,text,error);
  function openingResult(target,text){target.replaceChildren();const badge=target.closest('section')?.querySelector('.gate-badge');if(badge){badge.classList.remove('gate-opening');void badge.offsetWidth;badge.classList.add('gate-opening');}target.append(el('strong',text),el('p','La orden se envió correctamente. Comprueba que el portón se abra.'));target.className='message success opening-result';target.setAttribute('role','status');target.tabIndex=-1;target.focus({preventScroll:true});target.scrollIntoView({block:'center',behavior:'instant'});}
  const date=value=>value?new Date(value).toLocaleString():'Sin vencimiento';
  const states={active:'Activo',inactive:'Inactivo',suspended:'Suspendido',revoked:'Revocado',expired:'Vencido',pending:'En curso / revisión',uncertain:'Requiere revisión',used:'Utilizado',sent:'Orden enviada',not_sent:'No enviada',closed:'Revisión cerrada'};
  const status=c=>c.status==='active'&&c.expires_at&&c.expires_at<=Date.now()?'Vencido':(states[c.status]||c.status);
  let securityScript,securityQueue=Promise.resolve();
  function loadSecurity(){
    if(window.turnstile)return Promise.resolve();
    if(securityScript)return securityScript;
    securityScript=new Promise((resolve,reject)=>{
      const script=document.createElement('script');let settled=false;
      const finish=error=>{if(settled)return;settled=true;clearTimeout(timer);if(error){script.remove();securityScript=null;reject(error);}else resolve();};
      const timer=setTimeout(()=>finish(Error('No se pudo cargar la verificación. Revisa tu conexión e intenta de nuevo.')),15000);
      script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;
      script.onload=()=>finish(window.turnstile?null:Error('La verificación no está disponible. Intenta de nuevo.'));
      script.onerror=()=>finish(Error('No se pudo cargar la verificación. Revisa tu conexión e intenta de nuevo.'));
      document.head.append(script);
    });return securityScript;
  }
  function securityToken(action){
    const task=securityQueue.catch(()=>{}).then(async()=>{
      if(!config.turnstileSiteKey)throw Error('La verificación de seguridad no está disponible. Intenta más tarde.');
      const card=el('div',undefined,'security-check'),label=el('p','Verificando conexión segura…'),host=el('div');label.setAttribute('role','status');card.append(label,host);view.prepend(card);
      let widget;
      try{
        await loadSecurity();
        return await new Promise((resolve,reject)=>{
          let settled=false;const finish=(error,token)=>{if(settled)return;settled=true;clearTimeout(timer);error?reject(error):resolve(token);};
          const timer=setTimeout(()=>finish(Error('La verificación tardó demasiado. Intenta de nuevo.')),120000);
          try{widget=window.turnstile.render(host,{sitekey:config.turnstileSiteKey,action,language:'es',theme:'light',size:'flexible',appearance:'interaction-only',retry:'never',
            callback:token=>finish(null,token),
            'error-callback':()=>{finish(Error('No pudimos verificar la conexión. Intenta de nuevo.'));return true;},
            'expired-callback':()=>finish(Error('La verificación venció. Intenta de nuevo.')),
            'timeout-callback':()=>finish(Error('La verificación venció. Intenta de nuevo.')),
            'before-interactive-callback':()=>{label.textContent='Completa la verificación para continuar.';card.scrollIntoView({block:'center'});}
          });}catch{finish(Error('No se pudo iniciar la verificación. Intenta de nuevo.'));}
        });
      }finally{if(widget!==undefined)window.turnstile?.remove(widget);card.remove();}
    });securityQueue=task;return task;
  }
  async function api(path,body){
    const action=path.endsWith('/login')?'login':/\/api\/(access-state|open)$/.test(path)?'visitor':null;
    const token=config.turnstileRequired&&body!==undefined&&action?await securityToken(action):null;
    let r;try{r=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json',...(token?{'X-Turnstile-Token':token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});}catch{throw Error('Sin conexión. Actualiza los datos antes de repetir una operación.');}
    let data;try{data=await r.json();}catch{throw Error(r.status===429?'Demasiadas solicitudes. Espera un momento antes de intentar de nuevo.':'Respuesta inesperada del servidor');}
    if(!r.ok||!data.ok){if(r.status===401){location.href=platform?'/platform':base;}const error=Error(data.error||'No se pudo completar la operación');error.operationClosed=data.operationClosed;throw error;}
    return data;
  }
  const iconPaths={settings:'M4 7h16M4 17h16M8 4v6M16 14v6',gate:'M3 21V4h18v17M3 7h18M7 7v14M12 7v14M17 7v14M2 21h20',codes:'M4 4h16v16H4zM8 8h8M8 12h5M8 16h7',history:'M3 11a9 9 0 1 1 3 8M3 4v7h7M12 7v5l3 2',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M13 4a4 4 0 0 1 0 8M22 21v-2a4 4 0 0 0-3-3.87M13 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0',building:'M4 21V3h12v18M16 10h4v11M8 7h4M8 11h4M8 15h4M2 21h20',chart:'M4 20V4M4 20h17M9 16v-5M14 16V7M19 16v-8',logout:'M9 21H4V3h5M14 8l5 4-5 4M8 12h11',plus:'M12 5v14M5 12h14',refresh:'M20 7v5h-5M4 17v-5h5M6 6a8 8 0 0 1 13 3M18 18a8 8 0 0 1-13-3'};
  function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.7');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',iconPaths[name]||iconPaths.gate);svg.append(path);return svg;}
  function gateBadge(){const d=el('div',undefined,'gate-badge'),svg=icon('gate');svg.replaceChildren();for(const [cls,path] of [['gate-frame','M2 21V3h20v18'],['gate-left','M4 6h8v14H4zM8 6v14'],['gate-right','M12 6h8v14h-8zM16 6v14']]){const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('class',cls);p.setAttribute('d',path);svg.append(p);}d.append(svg);return d;}
  function markNav(name){for(const b of document.querySelectorAll('#nav button,.mobile-tabs button')){const active=b.dataset.label===name;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}if($('view-label'))$('view-label').textContent=name;}
  function stat(value,label,symbol,role=false){const d=el('div',undefined,'stat-card'),badge=el('div',undefined,'stat-icon'),text=el('div');badge.append(icon(symbol));text.append(el('div',value,'stat-value'+(role?' role':'')),el('div',label,'stat-label'));d.append(badge,text);return d;}
  function heading(title,subtitle){const d=el('div',undefined,'view-heading');d.append(el('h2',title),el('p',subtitle));return d;}
  function button(text,action,cls=''){
    const b=el('button',text,cls);b.type='button';b.dataset.label=text;const symbols={'Inicio':'chart','Abrir portón':'gate','Portones':'gate','Códigos':'codes','Historial':'history','Usuarios':'users','Edificios':'building','Configuración':'settings','Reportes':'chart','Auditoría':'history','Cerrar sesión':'logout','Crear código':'plus','Crear edificio':'plus','Agregar usuario':'plus','Agregar portón':'plus','Actualizar':'refresh'};if(symbols[text])b.prepend(icon(symbols[text]));
    b.addEventListener('click',async()=>{if(b.disabled)return;b.disabled=true;try{await action();}catch(e){message(e.message,true);}finally{b.disabled=false;}});return b;
  }
  function section(title){const s=el('section');s.append(el('h2',title));return s;}
  function table(parent,headers,rows){const wrap=el('div',undefined,'scroll'),t=el('table',undefined,headers.length>=6?'wide-table':headers.length>=4?'medium-table':''),head=el('thead'),tr=el('tr');headers.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const body=el('tbody');
    if(!rows.length){const row=el('tr'),cell=el('td','No hay registros');cell.colSpan=headers.length;row.append(cell);body.append(row);}
    rows.forEach(values=>{const row=el('tr');values.forEach(v=>{const cell=el('td');cell.dataset.label=headers[row.children.length];if(typeof v==='string'&&['Activo','Orden enviada','Inactivo','Suspendido','Revocado','Vencido','Requiere revisión','En curso / revisión','Utilizado'].includes(v)){cell.append(el('span',v,'status-pill '+(['Activo','Orden enviada'].includes(v)?'good':['Requiere revisión','En curso / revisión'].includes(v)?'warn':['Inactivo','Suspendido','Revocado','Vencido'].includes(v)?'bad':'')));}else cell.append(v instanceof Node?v:document.createTextNode(String(v??'—')));row.append(cell);});body.append(row);});t.append(body);wrap.append(t);parent.append(wrap);
  }
  function actions(...buttons){const d=el('div',undefined,'actions');d.append(...buttons);return d;}
  function filterLayout(form){form.classList.add('filter-form');for(const label of [...form.querySelectorAll(':scope > label')]){const field=el('div',undefined,'field'),control=label.nextElementSibling;label.before(field);field.append(label,control);}}
  function passCards(parent,items,tenant){const grid=el('div',undefined,'pass-grid');for(const c of items){const card=el('article',undefined,'pass-card'),top=el('div',undefined,'pass-top');top.append(el('h3',c.label||'Acceso de visita'),el('span',status(c),'status-pill '+(status(c)==='Activo'?'good':['uncertain','pending'].includes(c.status)?'warn':'')));card.append(top,el('p',c.gate_name||'Portón no disponible','pass-gate'),el('code',c.code),el('p',c.visit_mode?'Una visita · 10 minutos':c.single_use?'Un solo uso':c.expires_at?'Reutilizable':'Sin vencimiento','muted'));
    const expiry=el('p',undefined,'muted'),track=el('div',undefined,'expiry-track'),fill=el('div');track.append(fill);card.append(track,expiry);
    const paint=()=>{const left=c.expires_at-Date.now();expiry.textContent=c.expires_at?(c.visit_mode&&!c.visit_started_at?'Puede comenzar hasta: ':'Vence: ')+date(c.expires_at)+(left>0&&left<3600000?' · '+Math.ceil(left/60000)+' min restantes':''):'Vigente hasta que lo revoques';fill.style.width=(c.expires_at?Math.max(0,Math.min(100,100*left/Math.max(1,c.expires_at-(c.visit_started_at||c.created_at)))):100)+'%';};paint();const timer=setInterval(()=>{if(!card.isConnected){clearInterval(timer);return;}paint();if(c.expires_at&&c.expires_at<=Date.now()){top.lastChild.textContent='Vencido';top.lastChild.className='status-pill';for(const b of card.querySelectorAll('button'))if(['Compartir','Copiar'].includes(b.dataset.label))b.disabled=true;}},15000);
    const buttons=[];if(status(c)==='Activo')buttons.push(button('Compartir',()=>codeResult(c,tenant),'secondary'),button('Copiar',async()=>{await navigator.clipboard.writeText(location.origin+'/t/'+tenant.slug+'?code='+encodeURIComponent(c.code));message('Enlace de acceso copiado.');},'secondary'));
    if(['active','pending','uncertain'].includes(c.status))buttons.push(button('Revocar',async()=>{if(!confirm('¿Revocar este acceso? Una orden ya enviada no se cancela.'))return;await api(base+'/admin/revoke-code',{code:c.code});await codes();},'danger'));card.append(actions(...buttons));grid.append(card);
  }if(!items.length)grid.append(el('p','No hay pases con estos filtros. Crea uno para compartir acceso.','empty-state'));parent.append(grid);}
  function input(form,label,type='text',value='',required=true){const id='f-'+crypto.randomUUID(),l=el('label',label);l.htmlFor=id;const n=el('input');n.id=id;n.type=type;n.value=value;n.required=required;if(type==='password'){n.autocomplete='new-password';n.minLength=8;n.maxLength=128;}else n.maxLength=2048;form.append(l,n);if(type==='password'){const toggle=button('Mostrar contraseña',()=>{const show=n.type==='password';n.type=show?'text':'password';toggle.textContent=show?'Ocultar contraseña':'Mostrar contraseña';toggle.setAttribute('aria-pressed',String(show));},'secondary password-toggle');toggle.setAttribute('aria-pressed','false');form.append(toggle);}return n;}
  function select(form,label,options,value=''){const id='f-'+crypto.randomUUID(),l=el('label',label);l.htmlFor=id;const n=el('select');n.id=id;n.required=true;options.forEach(([v,name])=>{const o=el('option',name);o.value=v;n.append(o);});n.value=value;form.append(l,n);return n;}
  function gateChecks(form,gates,selected=[]){const field=el('fieldset');field.append(el('legend','Portones autorizados'));const checks=[];gates.filter(g=>g.status==='active').forEach(g=>{const label=el('label'),c=el('input');c.type='checkbox';c.value=g.id;c.checked=selected.includes(g.id);label.append(c,document.createTextNode(g.name));field.append(label);checks.push(c);});if(!checks.length)field.append(el('p','No hay portones activos. El usuario quedará sin acceso.'));form.append(field);return ()=>checks.filter(c=>c.checked).map(c=>c.value);}
  function dialog(title,build,submit,label='Guardar'){
    const d=el('dialog'),form=el('form'),error=el('div',undefined,'message error');error.setAttribute('role','alert');form.append(el('h2',title));const fields=build(form);const save=el('button',label);save.type='submit';form.append(error,actions(button('Cancelar',()=>d.close(),'secondary'),save));d.append(form);document.body.append(d);
    form.addEventListener('submit',async event=>{event.preventDefault();save.disabled=true;error.textContent='';try{await submit(fields);d.close();}catch(e){error.textContent=e.message;}finally{save.disabled=false;}});
    d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d;
  }
  async function screen(loader){const rev=++revision;view.replaceChildren(el('p','Cargando…'));message('');try{const result=await loader();if(rev===revision)view.replaceChildren(result);}catch(e){if(rev===revision){view.replaceChildren();message(e.message,true);}}}
  function codeResult(c,tenant){const text=`Edificio: ${tenant.name}\nPortón: ${c.gate_name}\nCódigo: ${c.code}\nPara: ${c.label}\n${c.visit_mode&&!c.visit_started_at?'Puede comenzar hasta':'Vigencia'}: ${date(c.expires_at)}\nTipo: ${c.visit_mode?'Una visita · 10 minutos':c.single_use?'Un solo uso':!c.expires_at?'Sin vencimiento':'Reutilizable'}\n${location.origin}/t/${tenant.slug}/?code=${encodeURIComponent(c.code)}`;
    const d=el('dialog');d.className='code-result';d.append(el('h2','Compartir acceso'),el('p',tenant.name+' · '+c.gate_name,'muted'),el('code',c.code,'result-number'),el('p',text,'result-details'));const link=el('a','Compartir por WhatsApp','button');link.href='https://wa.me/?text='+encodeURIComponent(text);link.target='_blank';link.rel='noopener noreferrer';d.append(actions(button('Copiar',async()=>{await navigator.clipboard.writeText(text);message('Acceso copiado');}),link,button('Cerrar',()=>d.close(),'secondary')));d.addEventListener('close',()=>d.remove(),{once:true});document.body.append(d);d.showModal();
  }
  async function codeTable(parent,tenant,platformView=false){
    const path=platformView?'/platform/api/codes?tenantId='+encodeURIComponent(tenant.id):base+'/admin/codes';
    const outer=parent,key=(platformView?'platform:':'tenant:')+tenant.id;let filters=codeFilters.get(key)||{page:0,search:'',status:'current'};codeFilters.set(key,filters);
    let content=outer.querySelector('[data-code-list]');if(!content){content=el('div');content.dataset.codeList='true';outer.append(content);}parent=content;parent.replaceChildren();
    const form=el('form'),search=input(form,'Buscar código exacto','text',filters.search,false),state=select(form,'Estado del código',[['current','Vigentes y por revisar'],['','Todos, incluidos anteriores'],['active','Activo'],['pending','En curso'],['uncertain','Requiere revisión'],['revoked','Revocado'],['used','Utilizado'],['expired','Vencido']],filters.status);search.maxLength=64;state.required=false;
    const apply=el('button','Buscar');apply.type='submit';form.append(apply);form.addEventListener('submit',async e=>{e.preventDefault();filters.page=0;filters.search=search.value.trim();filters.status=filters.search&&state.value==='current'?'':state.value;apply.disabled=true;try{await codeTable(outer,tenant,platformView);}catch(e){message(e.message,true);}finally{apply.disabled=false;}});filterLayout(form);parent.append(form);
    const data=await api(path+(path.includes('?')?'&':'?')+new URLSearchParams(filters));parent.append(el('p','Página '+(filters.page+1)+' · hasta 100 códigos. Usa la búsqueda para encontrar cualquier código anterior.','muted'));
    if(!platformView&&config.user.role!=='master')passCards(parent,data.codes,tenant);else {parent.classList.add('access-cards');table(parent,['Código','Nota','Portón','Creado por','Tipo','Vencimiento','Estado','Acciones'],data.codes.map(c=>{
      const buttons=[];
      if(['pending','uncertain'].includes(c.status))buttons.push(button('Revocar',async()=>{if(!confirm('¿Revocar futuras aperturas? Una orden ya enviada no puede cancelarse.'))return;await api(platformView?'/platform/api/codes/revoke':base+'/admin/revoke-code',{tenantId:tenant.id,code:c.code});await codeTable(outer,tenant,platformView);},'danger'));
      if(status(c)==='Activo'){
        buttons.push(button('Compartir',()=>codeResult(c,tenant),'secondary'));
        buttons.push(button('Revocar',async()=>{if(!confirm('¿Revocar este código?'))return;await api(platformView?'/platform/api/codes/revoke':base+'/admin/revoke-code',{tenantId:tenant.id,code:c.code});await (platformView?building(tenant):codes());},'danger'));
      }
      if(platformView&&['pending','uncertain'].includes(c.status)){
        buttons.push(button('Resolver',()=>dialog('Revisar apertura de '+c.gate_name,f=>{f.append(el('p','Comprueba físicamente si la orden se ejecutó. Permitir otro intento puede causar una segunda apertura. Una solicitud reciente no se puede liberar hasta pasados dos minutos.'));return select(f,'Resultado',[['used','Cerrar el código sin permitir otro intento'],['retry','Permitir otro intento']],'used');},async choice=>{await api('/platform/api/codes/resolve',{tenantId:tenant.id,code:c.code,action:choice.value});await building(tenant);})));
      }
      return [el('code',c.code),c.label,c.gate_name||'Portón no disponible',c.owner,c.visit_mode?'Una visita · 10 minutos':c.single_use?'Un uso':!c.expires_at?'Sin vencimiento':'Reutilizable',date(c.expires_at),status(c),actions(...buttons)];
    }));}
    const prev=button('Página anterior',async()=>{filters.page--;await codeTable(outer,tenant,platformView);},'secondary'),next=button('Página siguiente',async()=>{filters.page++;await codeTable(outer,tenant,platformView);},'secondary');prev.disabled=filters.page===0;next.disabled=data.codes.length<100;parent.append(actions(prev,next));
  }
  async function newCode(){
    const {gates}=await api(base+'/admin/gates');if(!gates.length)throw Error('No tienes portones disponibles. Solicita permisos al administrador.');
    const d=el('dialog'),form=el('form'),progress=el('p','Paso 1 de 3','wizard-progress'),track=el('div',undefined,'wizard-track'),fill=el('div',undefined,'wizard-fill');track.append(fill);form.noValidate=true;form.append(el('h2','Nuevo código'),progress,track);
    const steps=[el('div',undefined,'wizard-step'),el('div',undefined,'wizard-step'),el('div',undefined,'wizard-step')];
    steps[0].append(el('p','¿Para quién es este acceso?','muted'));
    const gate=select(steps[0],'Portón',gates.length===1?gates.map(g=>[g.id,g.name]):[['','Selecciona un portón'],...gates.map(g=>[g.id,g.name])],gates.length===1?gates[0].id:''),label=input(steps[0],'Nombre o nota');label.placeholder='Ej. Visita de Ana';label.maxLength=60;
    steps[1].append(el('p','Define cómo se podrá utilizar.','muted'));
    const type=select(steps[1],'Tipo',[['visit','Una visita · 10 minutos'],['repeat','Reutilizable con vencimiento'],['unlimited','Sin vencimiento']],'visit'),duration=el('div');steps[1].append(duration);
    const preset=select(duration,'Puede comenzar hasta',[['30','En 30 minutos'],['120','En 2 horas'],['360','En 6 horas'],['1440','En 24 horas'],['today','Hoy'],['tomorrow','Mañana'],['custom','Elegir fecha']],'today'),dateBox=el('div');duration.append(dateBox);const until=input(dateBox,'Fecha y hora límite','datetime-local');const hint=el('p',undefined,'muted');steps[1].append(hint);
    function deadline(){if(/^\d+$/.test(preset.value))return Date.now()+Number(preset.value)*60000;if(preset.value==='custom')return new Date(until.value).getTime();const d=new Date();if(preset.value==='tomorrow')d.setDate(d.getDate()+1);d.setHours(23,59,59,999);return d.getTime();}
    function durationUI(){const unlimited=type.value==='unlimited';duration.hidden=unlimited;preset.disabled=unlimited;dateBox.hidden=preset.value!=='custom';until.disabled=unlimited||preset.value!=='custom';duration.querySelector('label').textContent=type.value==='visit'?'Puede comenzar hasta':'El acceso vence';hint.textContent=unlimited?'Puede usarse hasta que canceles el acceso.':type.value==='visit'?'Una vez que abras, tendrás 10 minutos para volver a abrir.':'Puede abrir varias veces hasta la fecha indicada.';}
    type.addEventListener('change',durationUI);preset.addEventListener('change',durationUI);durationUI();
    steps[2].append(el('p','Confirma el portón y la vigencia antes de crear el código.','muted'));const summary=el('dl',undefined,'wizard-summary');steps[2].append(summary);form.append(...steps);
    let step=0,busy=false;
    const error=el('div',undefined,'message error');error.setAttribute('role','alert');
    const back=button('Atrás',()=>{if(step){step--;render();}},'secondary'),cancel=button('Cancelar',()=>d.close(),'secondary'),next=el('button','Siguiente');next.type='submit';
    form.append(error,actions(cancel,back,next));d.append(form);document.body.append(d);
    function render(){steps.forEach((s,i)=>{s.hidden=i!==step;});progress.textContent='Paso '+(step+1)+' de 3';fill.style.width=((step+1)/3*100)+'%';back.hidden=step===0;next.textContent=step===2?'Crear código':'Siguiente';error.textContent='';if(step===2){summary.replaceChildren();for(const [k,v] of [['Para',label.value.trim()],['Portón',gate.selectedOptions[0]?.textContent||''],['Tipo',type.selectedOptions[0].textContent],[type.value==='visit'?'Puede comenzar hasta':'Vence',type.value==='unlimited'?'Sin vencimiento':date(deadline())]])summary.append(el('dt',k),el('dd',v));}}
    form.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;for(const input of steps[step].querySelectorAll('input,select'))if(!input.reportValidity())return;if(step===0&&!label.value.trim()){error.textContent='Escribe el nombre o nota';return;}if(step===1&&type.value!=='unlimited'&&(!Number.isFinite(deadline())||deadline()<=Date.now())){error.textContent='Elige una fecha y hora posteriores a este momento.';return;}if(step<2){step++;render();return;}
      busy=true;next.disabled=back.disabled=cancel.disabled=true;next.textContent='Creando…';
      try{const result=await api(base+'/admin/create-code',{gateId:gate.value,label:label.value.trim(),expiresAt:type.value==='unlimited'?null:deadline(),singleUse:false,visit:type.value==='visit'});d.close();await codes();codeResult(result.code,config.tenant);}catch(e){error.textContent=e.message;}finally{busy=false;next.disabled=back.disabled=cancel.disabled=false;next.textContent='Crear código';}
    });d.addEventListener('cancel',e=>{if(busy)e.preventDefault();});d.addEventListener('close',()=>d.remove(),{once:true});render();d.showModal();
  }
  async function sendGate(id,target=notice){const key='gate-order:'+config.tenant.id+':'+id;let requestId=sessionStorage.getItem(key);if(!requestId){requestId=crypto.randomUUID();sessionStorage.setItem(key,requestId);}try{const d=await api(base+'/admin/open-gate',{gateId:id,requestId});sessionStorage.removeItem(key);openingResult(target,d.message);}catch(e){if(e.operationClosed)sessionStorage.removeItem(key);feedback(target,e.message+(e.operationClosed?' Puedes enviar una orden nueva cuando el dispositivo esté disponible.':''),true);throw e;}}
  function gateCards(gates){const grid=el('div',undefined,'gate-grid');for(const g of gates){const card=el('section',undefined,'gate-card'),result=el('div');result.setAttribute('aria-live','polite');card.append(gateBadge(),el('h3',g.name),g.hasRelay?connectionBadge(g.connection_state,g.connection_checked_at):el('span','Acceso habilitado','status-pill'),el('p','Mantén presionado para enviar la orden.','muted'));
      let timer=null,busy=false;const control=el('button',undefined,'hold-button'),label=el('span','Mantener para abrir');control.type='button';control.setAttribute('aria-label','Mantener para abrir '+g.name);control.append(label);
      const cancel=()=>{clearTimeout(timer);timer=null;control.classList.remove('holding');if(!busy)label.textContent='Mantener para abrir';};
      const send=async()=>{cancel();if(busy||!control.isConnected)return;busy=true;control.disabled=true;label.textContent='Enviando…';try{await sendGate(g.id,result);}catch{}finally{busy=false;control.disabled=false;label.textContent='Mantener para abrir';}};
      const begin=()=>{if(busy||timer)return;result.replaceChildren();label.textContent='Sigue presionando…';control.classList.add('holding');timer=setTimeout(send,600);};
      control.addEventListener('pointerdown',e=>{if(e.button!==0||!e.isPrimary)return;begin();});for(const event of ['pointerup','pointerleave','pointercancel','lostpointercapture','blur'])control.addEventListener(event,cancel);
      control.addEventListener('keydown',e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();if(!e.repeat)begin();}});control.addEventListener('keyup',e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();cancel();}});control.addEventListener('contextmenu',e=>e.preventDefault());
      const confirmOpen=()=>dialog('Abrir '+g.name,f=>{f.append(el('p','Se enviará una orden únicamente a '+g.name+'. Comprueba que estás frente al acceso correcto.'));},async()=>sendGate(g.id,result),'Enviar orden');
      control.addEventListener('click',e=>{if(e.detail===0&&!busy&&!timer)confirmOpen();});
      const accessible=button('Abrir con confirmación',confirmOpen,'text-button');card.append(control,accessible,result);grid.append(card);
    }if(!gates.length)grid.append(el('p','Todavía no tienes portones asignados. Contacta al administrador.','empty-state'));return grid;
  }
  function chart(data){const s=section('Actividad por hora'),head=el('div',undefined,'section-header');head.append(s.firstChild,el('span','Últimas 24 horas','chart-caption'));s.append(head);const plot=el('div',undefined,'activity-chart'),labels=el('div',undefined,'chart-labels'),end=Math.floor(data.serverNow/3600000)*3600000,values=Array.from({length:24},(_,i)=>{const hour=end-(23-i)*3600000;return {hour,count:data.hours.find(h=>h.hour===hour)?.count||0};}),max=Math.max(1,...values.map(v=>v.count));plot.setAttribute('aria-hidden','true');for(const v of values){const bar=el('div',undefined,'activity-bar');bar.style.height=Math.max(1,v.count/max*100)+'%';bar.title=new Date(v.hour).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' · '+v.count+' órdenes';plot.append(bar);}for(const i of [0,6,12,18,23])labels.append(el('span',new Date(values[i].hour).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})));s.append(plot,labels,el('p','Órdenes con respuesta satisfactoria. No confirma la apertura física del portón. La última hora está en curso.','muted'));const details=el('details',undefined,'chart-details');details.append(el('summary','Ver cifras por hora'));table(details,['Hora','Órdenes enviadas'],values.map(v=>[date(v.hour),v.count]));s.append(details);return s;}
  async function codes(home=false){markNav(home?'Inicio':'Códigos');await screen(async()=>{
    const container=el('div'),master=config.user.role==='master';container.append(heading(home?(master?'Resumen del edificio':'Hola, '+config.user.username):'Códigos y pases',home?(master?config.tenant.name+' · Control de accesos':'Abre tus accesos y comparte un pase con tus visitas.'):'Administra la vigencia y comparte accesos de forma sencilla.'));
    const quick=el('div',undefined,'quick-actions');quick.append(button('Abrir portón',openGate),button('Invitar a alguien',newCode,'secondary'));container.append(quick);
    if(home){const [{gates},data]=await Promise.all([api(base+'/admin/gates'),master?api(base+'/admin/dashboard'):Promise.resolve(null)]);if(master){const stats=el('div',undefined,'stats-grid');stats.append(stat(data.sent,'Órdenes enviadas · 24 h','gate'),stat(data.attention,'Sin confirmar / no enviadas · 24 h','history'),stat(data.activeCodes,'Códigos activos','codes'),stat(data.lastSent?date(data.lastSent):'Sin actividad','Última orden enviada','chart',true));container.append(stats);if(data.attention){const note=el('div',undefined,'attention-note');note.append(el('span','Hay órdenes recientes sin confirmación o que no se enviaron.'),button('Ver historial',logs,'secondary'));container.append(note);}container.append(chart(data));}const access=section(master?'Accesos del edificio':'Mis accesos');access.append(el('p','La conexión corresponde a la última consulta; Sin verificar no significa desconectado.','muted'),gateCards(gates));container.append(access);}
    const s=section('Códigos de acceso'),head=el('div',undefined,'section-header');head.append(s.firstElementChild,button('Actualizar',()=>codes(home),'secondary'));s.append(head);await codeTable(s,config.tenant);container.append(s);return container;
  });}
  async function openGate(){const {gates}=await api(base+'/admin/gates');if(!gates.length)throw Error('No tienes portones disponibles');dialog('Abrir portón',f=>select(f,'Portón',[['','Selecciona un portón'],...gates.map(g=>[g.id,g.name])],gates.length===1?gates[0].id:''),async field=>sendGate(field.value),'Enviar orden');}
  async function logs(){markNav('Historial');await screen(async()=>{const s=section('Historial de órdenes'),data=await api(base+'/admin/logs');s.append(el('p',`Órdenes enviadas en las últimas 24 horas: ${data.opensLast24}`),el('p','Últimos 200 registros; se conservan 30 días. Los filtros y la exportación se aplican a estos registros. Una orden enviada no confirma la apertura física.','muted'));
    const filters=el('form'),search=input(filters,'Buscar en historial','search','',false),gate=select(filters,'Filtrar portón',[['','Todos los portones'],...[...new Map(data.logs.map(l=>[l.gate_id,l.gate_name||'Portón no disponible']))].map(([id,name])=>[id,name])]),outcome=select(filters,'Filtrar resultado',[['','Todos los resultados'],['sent','Orden enviada'],['not_sent','No enviada'],['uncertain','Requiere revisión'],['pending','En curso']]);gate.required=outcome.required=false;filterLayout(filters);const list=el('div',undefined,'access-cards');let visible=[];
    const columns=['Fecha y hora','Portón','Código','Nota','Usuario','Resultado'],values=l=>[date(l.at),l.gate_name||'Portón no disponible',l.code||'',l.label||'',l.owner||'',states[l.outcome]||l.outcome];
    function render(){const query=search.value.trim().toLocaleLowerCase();visible=data.logs.filter(l=>(!gate.value||l.gate_id===gate.value)&&(!outcome.value||l.outcome===outcome.value)&&(!query||values(l).join(' ').toLocaleLowerCase().includes(query)));list.replaceChildren();table(list,columns,visible.map(values));}
    for(const control of [search,gate,outcome])control.addEventListener('input',render);filters.addEventListener('submit',e=>e.preventDefault());s.append(filters,button('Exportar CSV',()=>{const cell=v=>'"'+String(/^[\s]*[=+@\-]/.test(String(v))?"'"+v:v).replaceAll('"','""')+'"';const csv='\uFEFF'+[columns,...visible.map(values)].map(row=>row.map(cell).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=el('a');link.href=url;link.download='portonsmart-historial.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'secondary'),list);render();return s;
  });}

  function welcomeUser(tenant,username,password,gates){
    const text='¡Bienvenido a '+tenant.name+'!\n\nEntra a tu panel: '+location.origin+'/t/'+tenant.slug+'?access=resident\nUsuario: '+username+(password?'\nContraseña: '+password:'\nUsa la contraseña que recibiste. Si no la recuerdas, contacta al administrador.')+'\n\n'+(gates.length?'Puedes abrir tus portones autorizados ('+gates.map(g=>g.name).join(', ')+'), crear códigos para tus visitas y consultar tu historial.':'Tu cuenta está lista. Solicita al administrador que te asigne un portón para comenzar.')+'\n\nPulsa “Entrar con mi usuario” e ingresa tus datos. Guarda este mensaje en privado.';
    const d=el('dialog');d.className='code-result';d.append(el('h2',password?'Usuario creado':'Compartir acceso de '+username),el('p','Revisa el mensaje y compártelo con este usuario.'),el('p',text,'result-details'));const link=el('a','Compartir bienvenida por WhatsApp','button');link.href='https://wa.me/?text='+encodeURIComponent(text);link.target='_blank';link.rel='noopener noreferrer';d.append(link,button('Cerrar',()=>d.close(),'secondary'));d.addEventListener('close',()=>d.remove(),{once:true});document.body.append(d);d.showModal();
  }
  async function userPanel(tenant,platformView=false){
    const s=section('Usuarios de '+tenant.name),suffix=platformView?'?tenantId='+encodeURIComponent(tenant.id):'';
    const [{users},{gates}]=await Promise.all([api(platformView?'/platform/api/users'+suffix:base+'/admin/users'),api(platformView?'/platform/api/gates'+suffix:base+'/admin/gates')]);
    const refresh=()=>platformView?building(tenant):usersView();
    const search=input(s,'Buscar usuario','search','',false);search.placeholder='Escribe el nombre de usuario';search.addEventListener('input',()=>{for(const row of s.querySelectorAll('tbody tr'))row.hidden=!row.cells[0].textContent.toLowerCase().includes(search.value.trim().toLowerCase());});s.append(button('Agregar usuario',()=>dialog('Nuevo usuario',f=>({name:input(f,'Usuario'),secret:input(f,'Contraseña (mínimo 8 caracteres)','password'),permissions:gateChecks(f,gates)}),async a=>{await api(platformView?'/platform/api/users':base+'/admin/create-user',{tenantId:tenant.id,username:a.name.value,secret:a.secret.value,gateIds:a.permissions()});await refresh();welcomeUser(tenant,a.name.value,a.secret.value,gates.filter(g=>a.permissions().includes(g.id)));})));
    table(s,['Usuario','Rol','Portones autorizados','Acciones'],users.map(u=>{
      const buttons=[button('Compartir',()=>welcomeUser(tenant,u.username,null,gates.filter(g=>g.status==='active'&&(u.role==='master'||u.gateIds.includes(g.id)))),'secondary'),button('Cambiar contraseña',()=>dialog('Contraseña de '+u.username,f=>input(f,'Nueva contraseña','password'),async secret=>{await api(platformView?'/platform/api/reset-secret':base+'/admin/users/reset',{tenantId:tenant.id,userId:u.id,secret:secret.value});message('Contraseña actualizada y sesiones anteriores invalidadas.');}))];
      if(u.role!=='master'){
        buttons.push(button('Permisos',()=>dialog('Permisos de '+u.username,f=>{f.append(el('p','Quitar un permiso revoca sus códigos activos de ese portón.'));return gateChecks(f,gates,u.gateIds);},async getIds=>{await api(platformView?'/platform/api/users/permissions':base+'/admin/users/permissions',{tenantId:tenant.id,userId:u.id,gateIds:getIds()});await refresh();}),'secondary'));
        buttons.push(button('Eliminar',async()=>{if(!confirm('¿Eliminar usuario y revocar sus códigos activos? Sus sesiones dejarán de funcionar.'))return;await api(platformView?'/platform/api/users/delete':base+'/admin/delete-user',{tenantId:tenant.id,userId:u.id});await refresh();},'danger'));
      }
      return [u.username,u.role==='master'?'Administrador':'Usuario',u.role==='master'?'Todos los portones activos':gates.filter(g=>u.gateIds.includes(g.id)).map(g=>g.name+(g.status!=='active'?' (inactivo)':'')).join(', ')||'Sin acceso',actions(...buttons)];
    }));return s;
  }
  async function gatesView(){markNav('Portones');await screen(async()=>{const s=section('Mis portones autorizados'),{gates}=await api(base+'/admin/gates');s.append(gateCards(gates),el('p','Conexión según la última consulta. Para cambiar la configuración, contacta al administrador de plataforma.','muted'));return s;});}
  async function usersView(){markNav('Usuarios');await screen(async()=>{const panel=await userPanel(config.tenant);panel.append(button('Configurar ayuda',()=>supportDialog(config.tenant,false),'secondary'));return panel;});}
  function supportDialog(tenant,platformView){dialog('Contacto de ayuda',f=>{f.append(el('p','Este número aparecerá para residentes y visitantes. Incluye el código de país. Déjalo vacío para retirarlo.'));return input(f,'Teléfono de WhatsApp','tel',tenant.support_phone||tenant.supportPhone||'',false);},async phone=>{const d=await api(platformView?'/platform/api/support':base+'/admin/support',{tenantId:tenant.id,phone:phone.value});tenant.supportPhone=tenant.support_phone=d.phone;message('Contacto de ayuda guardado.');});}
  function helpButton(){return button('Necesito ayuda',()=>{const d=dialog('Ayuda para entrar',f=>{f.append(el('p','Si tu acceso venció o fue cancelado, pide uno nuevo a quien te invitó.'),el('p','Si no se confirmó el envío, no repitas la apertura. Contacta al administrador para revisar lo ocurrido.'));if(config.tenant?.supportPhone){const link=el('a','Contactar por WhatsApp','button');link.href='https://wa.me/'+config.tenant.supportPhone+'?text='+encodeURIComponent('Hola, necesito ayuda para entrar a '+config.tenant.name+'.');link.target='_blank';link.rel='noopener noreferrer';f.append(link);}else f.append(el('p','Contacta a quien te invitó o a la administración del edificio.'));},async()=>{},'Entendido');},'secondary');}
  const connectionNames={online:'Conectado',offline:'Desconectado',initializing:'Iniciando',opening:'Relé activado',cooldown:'Pausa entre órdenes',unknown:'Sin verificar'};
  function connectionBadge(state,checked){
    const badge=el('span',undefined,'status-pill');
    const paint=()=>{const current=checked&&checked>Date.now()-120000?state:'unknown';badge.textContent=connectionNames[current]||'Sin verificar';badge.className='status-pill '+(current==='online'?'good':current==='offline'?'bad':current==='unknown'?'':'warn');};paint();
    if(checked&&checked>Date.now()-120000)setTimeout(()=>{if(badge.isConnected)paint();},Math.max(1,checked+120001-Date.now()));return badge;
  }
  function relaySelect(form,devices,current=''){
    const available=devices.filter(d=>!d.gate_id||d.device_id===current);
    const field=select(form,'Relé del inventario',[['',available.length?'Selecciona un relé':'No hay relés disponibles'],...available.map(d=>[d.device_id,d.name+' · '+d.device_id])],current);
    form.append(el('p','Registra o busca los dispositivos en Configuración. Un relé solo puede asignarse a un portón.','muted'));return field;
  }
  async function gateDialog(tenant,gate=null){
    const cfg=gate?JSON.parse(gate.trigger_config):{}, {devices}=await api('/platform/api/relay-inventory');
    dialog(gate?'Editar '+gate.name:'Nuevo portón',f=>{
      f.append(el('p','Cambiar la integración o deshabilitar el portón revoca sus códigos.','muted'));
      const name=input(f,'Nombre','text',gate?.name||''),type=select(f,'Cómo se controla',[['mqtt','Relé conectado (MQTT)'],['webhook','Enlace de activación HTTPS'],['demo','Demostración sin hardware']],gate?.trigger_type||'mqtt');
      const mqtt=el('div'),webhook=el('div'),device=relaySelect(mqtt,devices,cfg.deviceId||'');
      const url=input(webhook,'URL de activación HTTPS','url',cfg.url||''),method=select(webhook,'Método',[['GET','GET'],['POST','POST']],cfg.method||'GET');f.append(mqtt,webhook);
      const refresh=()=>{mqtt.hidden=type.value!=='mqtt';webhook.hidden=type.value!=='webhook';device.disabled=mqtt.hidden;url.disabled=method.disabled=webhook.hidden;};type.addEventListener('change',refresh);refresh();
      return {name,type,device,url,method,status:select(f,'Acceso',[['active','Habilitado'],['inactive','Deshabilitado']],gate?.status||'active')};
    },async a=>{await api('/platform/api/gates',{tenantId:tenant.id,gateId:gate?.id,name:a.name.value,triggerType:a.type.value,deviceId:a.device.value,triggerUrl:a.url.value,method:a.method.value,status:a.status.value});await building(tenant);});
  }
  function showConnection(c,name){
    dialog('Conexión de '+name,f=>{
      if(c.lock)f.append(el('p',c.lock==='cooldown'?'Espera unos segundos entre órdenes.':'Hay una orden pendiente de confirmación o revisión para este relé.'));
      f.append(el('p',c.ready?'Dispositivo conectado y listo para recibir una orden.':'El dispositivo no está listo para recibir órdenes.'),connectionBadge(c.connectionState,c.observedAt),
        el('p','Relé: '+c.deviceId),el('p','Consulta: '+date(c.observedAt)),el('p','Último reporte de salud: '+(c.health?.sampled_at?date(c.health.sampled_at*1000):'No disponible')),
        el('p','Disponibilidad MQTT: '+(c.availability??'Firmware anterior')),el('p','Último motivo de reinicio reportado: '+(c.health?.reset_reason||'No disponible')),el('p','Firmware: '+(c.health?.firmware_revision||'No informado')),el('p','Tiempo encendido al último reporte: '+(Number.isFinite(c.health?.uptime_s)?c.health.uptime_s+' segundos':'No disponible')),el('p','Pulso configurado: '+(c.info?.pulse_ms??'—')+' ms'),el('p','Señal WiFi: '+(c.health?.rssi??'—')+' dBm'),el('p','Esta consulta no acciona el relé. La conexión no indica si el portón está abierto o cerrado.','muted'));
    },async()=>{},'Cerrar');
  }
  async function connection(tenant,gate){
    let result;try{result=await api('/platform/api/gates/connection',{tenantId:tenant.id,gateId:gate.id});}finally{await building(tenant);}
    showConnection(result.connection,gate.name);
  }
  async function inventoryConnection(device){
    let result;try{result=await api('/platform/api/relay-inventory/connection',{deviceId:device.device_id});}finally{await configuration();}
    showConnection(result.connection,device.name);
  }
  function registerDevice(device=null){dialog(device?'Nombre del relé':'Registrar relé',f=>{
    f.append(el('p','El identificador debe coincidir con el configurado en el dispositivo. Puedes registrarlo aunque esté desconectado.'));
    const name=input(f,'Nombre del relé','text',device?.name||''),id=input(f,'Identificador del relé','text',device?.device_id||'');id.disabled=Boolean(device);return {name,id};
  },async a=>{await api('/platform/api/relay-inventory',{name:a.name.value,deviceId:a.id.value});await configuration();});}
  async function configuration(){markNav('Configuración');await screen(async()=>{
    const [{settings},{devices}]=await Promise.all([api('/platform/api/relay-settings'),api('/platform/api/relay-inventory')]);
    const container=el('div');container.append(heading('Configuración','Conexión MQTT e inventario de dispositivos de la plataforma.'));
    const server=section('Servidor MQTT');server.append(el('p',settings.broker+':'+settings.port+settings.path,'mqtt-endpoint'),el('p',settings.configured?'Cuentas centrales guardadas.':'Falta configurar las cuentas centrales.'),button('Editar conexión MQTT',relaySettings,'secondary'));container.append(server);
    const inventory=section('Inventario de relés');inventory.append(el('p','Busca dispositivos que hayan publicado su estado o regístralos manualmente. Después podrás asignarlos a un edificio.','muted'),
      actions(button('Buscar relés',async()=>{const d=await api('/platform/api/relay-inventory/discover',{});await configuration();message(d.found+' relés encontrados.'+(d.truncated?' Se alcanzó el límite de la consulta; puedes registrar los demás manualmente.':''));}),button('Registrar relé',()=>registerDevice(),'secondary'),button('Actualizar lista',configuration,'secondary')),
      el('p','La conexión muestra la última consulta y pasa a Sin verificar después de dos minutos. Actualizar lista no consulta el servidor MQTT; usa Buscar relés o Comprobar conexión.','muted'));
    inventory.classList.add('access-cards');table(inventory,['Relé','Identificador','Asignado a','Conexión','Última consulta','Acciones'],devices.map(d=>[d.name,d.device_id,d.gate_id?d.tenant_name+' · '+d.gate_name:'Disponible para asignar',connectionBadge(d.connection_state,d.checked_at),d.checked_at?date(d.checked_at):'Sin consultar',actions(button('Comprobar conexión',()=>inventoryConnection(d),'secondary'),button('Editar nombre',()=>registerDevice(d),'secondary'))]));container.append(inventory);return container;
  });}
  async function relaySettings(){
    const {settings}=await api('/platform/api/relay-settings');
    dialog('Conexión MQTT',f=>{
      f.append(el('p','Configura el servidor y las dos cuentas centrales que usará la plataforma.'),el('p',settings.configured?'Deja las contraseñas vacías para conservarlas.':'Escribe las credenciales de ambas cuentas.'));
      const broker=input(f,'Servidor MQTT','text',settings.broker),port=input(f,'Puerto WebSocket seguro','number',settings.port),path=input(f,'Ruta WebSocket','text',settings.path);port.min=1;port.max=65535;port.step=1;
      f.append(el('p','Usa el puerto WebSocket con TLS de tu proveedor; puede ser distinto del puerto TCP configurado en el relé. Cambiar el servidor aquí no reconfigura los dispositivos.','muted'),el('h3','Cuenta para enviar órdenes'));
      const commandUsername=input(f,'Usuario de envío','text',settings.commandUsername),commandPassword=input(f,'Contraseña de envío','password','',!settings.configured);commandPassword.minLength=1;commandPassword.maxLength=1024;
      f.append(el('h3','Cuenta para consultar dispositivos'));
      const statusUsername=input(f,'Usuario de consulta','text',settings.statusUsername),statusPassword=input(f,'Contraseña de consulta','password','',!settings.configured);statusPassword.minLength=1;statusPassword.maxLength=1024;
      f.append(el('p','Las contraseñas se guardan cifradas. La consulta necesita acceso a gate/+/# para encontrar los relés.','muted'));
      const currentSecret=input(f,'Tu contraseña de plataforma para confirmar','password');currentSecret.autocomplete='current-password';
      return {broker,port,path,commandUsername,commandPassword,statusUsername,statusPassword,currentSecret};
    },async fields=>{await api('/platform/api/relay-settings',Object.fromEntries(Object.entries(fields).map(([key,input])=>[key,input.value])));await configuration();message('Conexión MQTT guardada. Comprueba los dispositivos con la nueva configuración.');});
  }
  async function building(tenant){markNav('Edificios');await screen(async()=>{
    const container=el('div'),head=section(tenant.name);head.append(el('p','Edificio: '+tenant.slug),button('Configurar ayuda',()=>supportDialog(tenant,true),'secondary'),button('Volver a edificios',tenants,'secondary'));container.append(head);
    const gatesSection=section('Portones registrados'),{gates}=await api('/platform/api/gates?tenantId='+encodeURIComponent(tenant.id));gatesSection.append(button('Agregar portón',()=>gateDialog(tenant)));
    table(gatesSection,['Nombre','Acceso','Conexión del relé','Integración','Acciones'],gates.map(g=>{const c=JSON.parse(g.trigger_config);let host='Configuración inválida';try{host=g.trigger_type==='mqtt'?'Relé · '+c.deviceId:g.trigger_type==='demo'?'DEMO · no opera hardware':new URL(c.url).hostname;}catch{}return [g.name,g.status==='active'?'Habilitado':'Deshabilitado',g.trigger_type==='mqtt'?connectionBadge(g.connection_state,g.connection_checked_at):'No aplica',host,actions(button('Editar',()=>gateDialog(tenant,g),'secondary'),...(g.trigger_type==='mqtt'?[button('Comprobar conexión',()=>connection(tenant,g),'secondary')]:[]))];}));container.append(gatesSection);
    const relayPending=await api('/platform/api/relays?tenantId='+encodeURIComponent(tenant.id));
    if(relayPending.commands.length){const relaySection=section('Relés que necesitan revisión');relaySection.append(el('p','Comprueba lo ocurrido en el lugar antes de liberar una orden sin confirmar. Después revisa también el código o la orden del panel correspondiente.'));
      table(relaySection,['Portón','Fecha','Estado','Acciones'],relayPending.commands.map(c=>[c.gate_name,date(c.created_at),states[c.status],button('Liberar después de revisar',async()=>{if(!confirm('¿Ya comprobaste lo ocurrido? Esto permite nuevas órdenes al relé y no lo activa.'))return;await api('/platform/api/relays/resolve',{tenantId:tenant.id,commandId:c.id});await building(tenant);},'secondary')]));container.append(relaySection);}

    const pendingSection=section('Órdenes del panel pendientes de revisión'),pending=await api('/platform/api/operations?tenantId='+encodeURIComponent(tenant.id));
    table(pendingSection,['Portón','Fecha','Estado','Acciones'],pending.operations.map(o=>[o.gate_name,date(o.created_at),states[o.status],button('Cerrar revisión',async()=>{if(!confirm('Comprueba físicamente el portón. Cerrar esta revisión permitirá nuevas órdenes y no enviará ninguna.'))return;await api('/platform/api/operations/resolve',{tenantId:tenant.id,operationId:o.id});await building(tenant);})]));container.append(pendingSection);
    container.append(await userPanel(tenant,true));const codeSection=section('Códigos de '+tenant.name);await codeTable(codeSection,tenant,true);container.append(codeSection);return container;
  });}
  async function newTenant(){const {devices}=await api('/platform/api/relay-inventory');dialog('Nuevo edificio',f=>{
    const name=input(f,'Nombre'),preview=el('p',undefined,'mqtt-endpoint'),hint=el('p','Se genera a partir del nombre. Si ya existe, añadiremos un número.','muted'),customBox=el('div');
    preview.setAttribute('aria-live','polite');
    const slug=input(customBox,'Enlace personalizado');slug.maxLength=64;slug.pattern='[a-z0-9]+(-[a-z0-9]+)*';slug.autocapitalize='none';slug.spellcheck=false;
    let custom=false;
    const generate=()=>name.value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,64).replace(/-+$/g,'')||'edificio';
    const update=()=>{customBox.hidden=!custom;slug.disabled=!custom;preview.textContent=name.value.trim()||custom?'Vista previa: '+location.origin+'/t/'+(custom?slug.value:generate()):'Escribe el nombre para ver el enlace.';hint.textContent=custom?'El enlace debe ser único. Usa minúsculas, números y guiones.':'Se genera a partir del nombre. Si ya existe, añadiremos un número.';toggle.textContent=custom?'Usar enlace automático':'Personalizar enlace';toggle.setAttribute('aria-expanded',String(custom));};
    const toggle=button('Personalizar enlace',()=>{custom=!custom;if(custom&&!slug.value)slug.value=generate();update();if(custom)slug.focus();},'secondary');
    name.addEventListener('input',update);slug.addEventListener('input',update);f.append(preview,hint,toggle,customBox);update();
    const gate=input(f,'Nombre del primer portón');
    const type=select(f,'Cómo se controla',[['mqtt','Relé conectado (MQTT)'],['webhook','Enlace de activación HTTPS'],['demo','Demostración sin hardware']],'mqtt');
    const mqtt=el('div'),webhook=el('div'),device=relaySelect(mqtt,devices),url=input(webhook,'URL de activación HTTPS','url'),method=select(webhook,'Método',[['GET','GET'],['POST','POST']],'GET');f.append(mqtt,webhook);
    const refresh=()=>{mqtt.hidden=type.value!=='mqtt';webhook.hidden=type.value!=='webhook';device.disabled=mqtt.hidden;url.disabled=method.disabled=webhook.hidden;};type.addEventListener('change',refresh);refresh();
    return {name,slug,getSlug:()=>custom?slug.value:undefined,gate,type,device,url,method,user:input(f,'Usuario administrador'),secret:input(f,'Contraseña del administrador','password')};
  },async a=>{const result=await api('/platform/api/tenants',{name:a.name.value,slug:a.getSlug(),gateName:a.gate.value,triggerType:a.type.value,deviceId:a.device.value,triggerUrl:a.url.value,method:a.method.value,masterUsername:a.user.value,masterSecret:a.secret.value});await tenants();message('Edificio creado. Enlace: '+location.origin+'/t/'+result.slug);});}
  async function tenants(){markNav('Edificios');await screen(async()=>{const s=section('Edificios'),{tenants:items}=await api('/platform/api/tenants'),container=el('div'),stats=el('div',undefined,'stats-grid');container.append(heading('Tu plataforma','Edificios, accesos y seguimiento en un solo lugar.'));stats.append(stat(items.length,'Edificios registrados','building'),stat(items.filter(t=>t.status==='active').length,'Edificios activos','users'),stat(items.reduce((n,t)=>n+t.gates.length,0),'Portones registrados','gate'),stat(items.reduce((n,t)=>n+(t.needs_review||0),0),'Pendientes de revisión','history'));container.append(stats);const header=el('div',undefined,'section-header');header.append(s.firstChild,button('Crear edificio',newTenant,'secondary'));s.append(header);s.classList.add('access-cards');
    table(s,['Edificio','Enlace','Estado','Portones registrados','Acciones'],items.map(t=>{const link=el('a','Abrir página');link.href='/t/'+encodeURIComponent(t.slug);link.target='_blank';link.rel='noopener';return [t.name+(t.needs_review?' · '+t.needs_review+' por revisar':!t.gates.length?' · Sin portones':''),link,states[t.status],t.gates.map(g=>g.name+(g.status==='inactive'?' (inactivo)':'')).join(', ')||'Sin portones',actions(button('Administrar',()=>building(t)),button(t.status==='active'?'Suspender':'Reactivar',async()=>{if(!confirm('¿Cambiar el estado de '+t.name+'?'))return;await api('/platform/api/tenants/status',{tenantId:t.id,status:t.status==='active'?'suspended':'active'});await tenants();},'secondary'))];}));container.append(s);return container;});}
  async function reports(){markNav('Reportes');await screen(async()=>{const s=section('Uso por edificio'),{report}=await api('/platform/api/reports');s.append(el('p','Las cifras cuentan órdenes con respuesta satisfactoria de la integración, no aperturas físicas confirmadas.','muted'));table(s,['Edificio','Estado','Códigos activos','Últimas 24 h','Últimos 7 días','Últimos 30 días'],report.map(r=>[r.name,states[r.status],r.activeCodes,r.last24,r.last7,r.last30]));return s;});}
  async function audit(){markNav('Auditoría');await screen(async()=>{const s=section('Auditoría de plataforma'),{log}=await api('/platform/api/audit');s.append(el('p','Últimas 200 acciones','muted'));table(s,['Fecha','Administrador','Acción','Detalle'],log.map(l=>[date(l.at),l.admin_username,l.action,l.details]));return s;});}
  function loginForm(platformLogin){const s=section(platformLogin?'Acceso a plataforma':'Acceso de residentes y administradores'),f=el('form');if(platformLogin)s.prepend(gateBadge());s.insertBefore(el('p',platformLogin?'Administra tus edificios y sus accesos.':'Ingresa a tu panel de accesos.','entry-subtitle'),s.lastElementChild.nextSibling);const name=input(f,'Usuario'),secret=input(f,'Contraseña','password');secret.minLength=1;secret.autocomplete='current-password';name.autocomplete='username';const submit=el('button','Entrar');submit.type='submit';const local=el('div');local.setAttribute('role','alert');f.append(submit,local);f.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;local.textContent='';try{await api(platformLogin?'/platform/login':base+'/api/login',{username:name.value,secret:secret.value});location.href=platformLogin?'/platform/admin':base+'/admin';}catch(err){feedback(local,err.message,true);}finally{submit.disabled=false;}});s.append(f);return s;}
  async function start(){
    if(config.mode==='platform-login'){view.append(loginForm(true));if(new URLSearchParams(location.search).get('passwordChanged')==='1'){message('Contraseña actualizada. Inicia sesión con tu nueva contraseña.');history.replaceState(null,'',location.pathname);}return;}
    if(config.mode==='public'){
      const params=new URLSearchParams(location.search),recoveryKey='visitor-access:'+config.tenant.id;
      let saved='';try{saved=sessionStorage.getItem(recoveryKey)||'';}catch{}
      const s=section('Abrir con código de visita'),f=el('form');s.append(el('p','Escribe tu código para enviar la orden al portón.','entry-subtitle'));f.className='visitor-form';
      const code=input(f,'Código de seis dígitos','text',params.get('code')||saved);code.inputMode='numeric';code.pattern='[0-9]{6}';code.maxLength=6;code.autocomplete='off';const residentEntry=params.get('access')==='resident';history.replaceState(null,'',location.pathname);
      const submit=el('button');submit.type='submit';submit.className='visitor-open';const symbol=gateBadge(),buttonLabel=el('span','Enviar orden de apertura');submit.append(symbol,buttonLabel);submit.setAttribute('aria-live','polite');function paintOpen(state){submit.dataset.state=state;buttonLabel.textContent=state==='sending'?'Enviando orden…':state==='confirmed'?'Orden confirmada':'Enviar orden de apertura';symbol.classList.toggle('gate-opening',state==='confirmed');}const result=el('div');result.setAttribute('role','status');const gateChoices=el('fieldset',undefined,'visitor-gates');gateChoices.hidden=true;f.append(gateChoices,submit,result);let selectedGate=null,choicesCode='',lookupTimer;let ticker,recoveryRevision=0;
      function showGates(gates,entered){const prior=choicesCode===entered?selectedGate:null;choicesCode=entered;selectedGate=gates.some(g=>g.id===prior)?prior:gates.length===1?gates[0].id:null;gateChoices.replaceChildren(el('legend','Elige el portón'));gateChoices.hidden=!gates.length;for(const g of gates){const label=el('label',undefined,'visitor-gate-choice'),radio=el('input');radio.type='radio';radio.name='visitor-gate';radio.value=g.id;radio.checked=selectedGate===g.id;radio.addEventListener('change',()=>{selectedGate=g.id;paintOpen('idle');});label.append(radio,el('span',g.name));gateChoices.append(label);}}

      function remember(){try{sessionStorage.setItem(recoveryKey,code.value.trim());}catch{}}
      function countdown(data){clearInterval(ticker);if(!data.visitExpiresAt)return;const remaining=el('p');result.append(remaining);const deadline=performance.now()+Math.max(0,data.visitExpiresAt-data.serverNow);const tick=()=>{const secs=Math.max(0,Math.ceil((deadline-performance.now())/1000));remaining.textContent=secs?'Puedes volver a abrir durante '+Math.floor(secs/60)+':'+String(secs%60).padStart(2,'0'):'Los 10 minutos terminaron. Solicita un nuevo código.';if(!secs||!remaining.isConnected)clearInterval(ticker);};ticker=setInterval(tick,1000);tick();}
      async function recover(){if(!/^\d{6}$/.test(code.value.trim()))return;const revision=++recoveryRevision;const data=await api(base+'/api/access-state',{code:code.value.trim()});if(revision!==recoveryRevision)return;showGates(data.gates||[],code.value.trim());feedback(result,data.message+(data.lastSentAt?' Último envío confirmado: '+date(data.lastSentAt)+'.':''),data.state!=='active');countdown(data);}
      const refresh=button('Actualizar estado del acceso',recover,'secondary');refresh.hidden=true;
      code.addEventListener('input',()=>{recoveryRevision++;clearInterval(ticker);clearTimeout(lookupTimer);selectedGate=null;choicesCode='';gateChoices.hidden=true;gateChoices.replaceChildren();paintOpen('idle');result.replaceChildren();refresh.hidden=true;if(/^\d{6}$/.test(code.value.trim()))lookupTimer=setTimeout(()=>recover().catch(err=>feedback(result,err.message,true)),350);try{sessionStorage.removeItem(recoveryKey);}catch{}});
      f.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;paintOpen('sending');recoveryRevision++;clearInterval(ticker);result.textContent='';remember();try{
        const entered=code.value.trim();const gateId=choicesCode===entered?selectedGate:null;let d=await api(base+'/api/open',{code:entered,...(gateId?{gateId}:{})});if(d.selectionRequired){showGates(d.gates,entered);feedback(result,'Elige el portón y después pulsa el botón de apertura.');gateChoices.querySelector('input')?.focus();return;}
        if(d.confirmationRequired){const accepted=await new Promise(resolve=>{const modal=dialog('Una visita · 10 minutos',f=>{f.append(el('p',d.message));return null;},async()=>resolve(true),'Estoy frente al portón, abrir');modal.addEventListener('close',()=>resolve(false),{once:true});});if(!accepted)return;d=await api(base+'/api/open',{code:entered,confirmVisit:true,gateId});}
        result.className='';result.replaceChildren();paintOpen('confirmed');submit.title=d.message;countdown(d);refresh.hidden=false;
      }catch(err){feedback(result,err.message,true);refresh.hidden=false;}finally{submit.disabled=false;if(submit.dataset.state!=='confirmed')paintOpen('idle');}});
      s.append(f,refresh,helpButton());
      const resident=loginForm(false),choices=el('div',undefined,'entry-choices');resident.append(helpButton());choices.setAttribute('aria-label','Elige cómo entrar');const visitButton=button('Tengo un código de visita',()=>choose(false)),residentButton=button('Entrar con mi usuario',()=>choose(true));choices.append(visitButton,residentButton);
      view.append(choices,s,resident);
      function choose(login){s.hidden=login;resident.hidden=!login;visitButton.setAttribute('aria-pressed',String(!login));residentButton.setAttribute('aria-pressed',String(login));}
      choose(residentEntry);if(code.value&&!residentEntry){refresh.hidden=false;recover().catch(err=>feedback(result,err.message,true));}
      return;
    }
    const closeMenu=()=>{document.body.classList.remove('menu-open');$('menu-toggle')?.setAttribute('aria-expanded','false');};$('menu-toggle')?.addEventListener('click',()=>{const open=document.body.classList.toggle('menu-open');$('menu-toggle').setAttribute('aria-expanded',String(open));});$('menu-overlay')?.addEventListener('click',closeMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});nav.addEventListener('click',e=>{if(e.target.closest('button'))closeMenu();});
    if(platform)nav.append(button('Resumen',()=>{location.href='/platform/admin';},'secondary'));
    if(platform)nav.append(button('Edificios',tenants),button('Configuración',configuration,'secondary'),button('Reportes',reports,'secondary'),button('Auditoría',audit,'secondary'),button('Cambiar mi contraseña',()=>dialog('Cambiar mi contraseña',f=>{f.append(el('p','Al guardar se cerrarán todas tus sesiones. Vuelve a entrar con la nueva contraseña.','muted'));const current=input(f,'Contraseña actual','password');current.autocomplete='current-password';current.minLength=1;return {current,next:input(f,'Nueva contraseña','password'),confirm:input(f,'Confirmar nueva contraseña','password')};},async a=>{if(a.next.value!==a.confirm.value)throw Error('Las contraseñas nuevas no coinciden.');await api('/platform/api/change-password',{currentSecret:a.current.value,newSecret:a.next.value,confirmSecret:a.confirm.value});location.href='/platform?passwordChanged=1';}),'secondary'));
    else {nav.append(button('Inicio',()=>{location.href=base+'/admin';},'secondary'),button('Códigos',codes,'secondary'),button('Portones',gatesView,'secondary'),button('Historial',logs,'secondary'));if(config.user.role==='master')nav.append(button('Usuarios',usersView,'secondary'));}
    nav.append(button('Cerrar sesión',async()=>{await api(platform?'/platform/logout':base+'/admin/logout',{});location.href=platform?'/platform':base;},'secondary'));
    if(!platform&&config.user.role!=='master'){const tabs=el('nav',undefined,'mobile-tabs');tabs.setAttribute('aria-label','Accesos rápidos');for(const [label,text,fn,symbol] of [['Inicio','Accesos',()=>codes(true),'gate'],['Códigos','Pases',codes,'codes'],['Historial','Historial',logs,'history']]){const b=button(text,fn);b.dataset.label=label;if(!b.querySelector('svg'))b.prepend(icon(symbol));tabs.append(b);}const more=button('Más',()=>{$('menu-toggle').click();});more.prepend(icon('settings'));tabs.append(more);document.body.append(tabs);}if(platform){if(config.view==='configuration')await configuration();else if(config.view==='reports')await reports();else if(config.view==='building'){const data=await api('/platform/api/tenants');const tenant=data.tenants.find(t=>t.id===config.tenantId);if(!tenant)throw Error('Edificio no disponible');await building(tenant);}else{await tenants();if(config.view==='new')await newTenant();}}else if(config.view==='users'&&config.user.role==='master')await usersView();else if(config.view==='logs')await logs();else await codes();
  }
  start().catch(e=>message(e.message,true));
}
