import {initNavigation,navigate,destroyNavigation} from './navigation.js';
import {api,config,date} from './api.js';
const norm=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const names={create_tenant:'Creó un edificio',set_tenant_status:'Cambió el estado del edificio',create_user:'Creó un usuario',delete_user:'Eliminó un usuario',set_permissions:'Cambió permisos',reset_secret:'Cambió una contraseña',revoke_code:'Revocó un código',relay_registered:'Registró un relé',relay_settings_updated:'Actualizó la conexión MQTT',set_support:'Actualizó el contacto de ayuda'};
export function superApp(){return {
 user:config.user,drawer:false,armed:null,toastMsg:'',toastOn:false,error:'',loading:true,q:'',tab:'todos',auditFilter:'todo',buildings:[],devices:[],audit:[],ayerTotal:0,now:Date.now(),versions:{},dismissed:[],manageLabel:'Administrar edificio',
 get initials(){return this.user.username.slice(0,2).toUpperCase();},closePanels(){this.drawer=false;},n(x){return Number(x).toLocaleString('es-MX');},
 async init(){initNavigation(this,['resumen','edificios','flota','auditoria','administradores','pendientes'],'resumen');await this.refresh();this._clock=setInterval(()=>{this.now=Date.now();},15000);},destroy(){destroyNavigation(this);clearInterval(this._clock);clearTimeout(this._tt);},
 async refresh(){this.loading=true;this.error='';try{const d=await api('/platform/api/panel?offset='+new Date().getTimezoneOffset());this.now=d.serverNow;this.buildings=d.buildings;this.devices=d.devices;this.ayerTotal=d.yesterday;this.audit=d.audit.map(a=>{let detail={};try{detail=JSON.parse(a.details);}catch{}const building=d.buildings.find(b=>b.id===detail.tenantId);return {id:a.id,actor:a.admin_username,action:(names[a.action]||a.action)+(building?' · '+building.name:''),ago:date(a.at),icon:'fa-clipboard-list',mine:a.admin_username===this.user.username};});}catch(e){this.error=e.message;}this.loading=false;},
 fresh(d){return d.checked_at>this.now-120000;},state(d){return this.fresh(d)?d.connection_state:'unknown';},connected(d){return ['online','opening','cooldown'].includes(this.state(d));},
 get devTotal(){return this.devices.length;},get devOnline(){return this.devices.filter(d=>this.connected(d)).length;},get devOffline(){return this.devices.filter(d=>this.state(d)==='offline').length;},get devUnknown(){return this.devTotal-this.devOnline-this.devOffline;},get todayTotal(){return this.buildings.reduce((n,b)=>n+b.today,0);},get delta(){return this.ayerTotal?Math.round((this.todayTotal/this.ayerTotal-1)*100):0;},get suspended(){return this.buildings.filter(b=>b.status==='suspended').length;},get maxToday(){return Math.max(1,...this.buildings.map(b=>b.today));},get pendingTotal(){return this.buildings.reduce((n,b)=>n+b.pending,0);},get pendingBuildings(){return this.buildings.filter(b=>b.pending);},
 buildingDevices(b){return this.devices.filter(d=>d.tenant_id===b.id);},health(b){if(b.status==='suspended')return {t:'Suspendido',c:'bg-gray-100 text-gray-600',i:'fa-solid fa-pause'};const ds=this.buildingDevices(b);if(b.pending)return {t:'Requiere revisión',c:'bg-amber-100 text-amber-700',i:'fa-solid fa-triangle-exclamation'};if(!ds.length)return {t:'Sin relés asignados',c:'bg-gray-100 text-gray-600',i:'fa-solid fa-minus'};if(ds.some(d=>this.state(d)==='offline'))return {t:'Desconectado',c:'bg-red-100 text-red-700',i:'fa-solid fa-xmark'};if(ds.some(d=>!this.connected(d)))return {t:'Sin verificar',c:'bg-gray-100 text-gray-600',i:'fa-solid fa-question'};return {t:'Conectado',c:'bg-green-100 text-green-700',i:'fa-solid fa-check'};},
 issue(b){return b.pending>0||this.buildingDevices(b).some(d=>this.state(d)==='offline');},get withIssues(){return this.buildings.filter(b=>this.issue(b)).length;},
 get filtered(){const q=norm(this.q.trim());return this.buildings.filter(b=>(!q||norm(b.name+' '+b.slug+' '+b.admin).includes(q))&&(this.tab==='todos'||(this.tab==='incidencias'?this.issue(b):b.status==='suspended'))).map(b=>({...b,total:this.buildingDevices(b).length,online:this.buildingDevices(b).filter(d=>this.connected(d)).length,statusLabel:b.status==='active'?'Activa':'Suspendida'})).sort((a,b)=>Number(this.issue(b))-Number(this.issue(a))||b.today-a.today);},accountClass(b){return b.status==='active'?'bg-gray-100 text-gray-700':'bg-amber-100 text-amber-700';},
 get alerts(){return this.buildings.filter(b=>this.issue(b)).map(b=>({id:b.id+':'+b.pending+':'+this.buildingDevices(b).map(d=>d.checked_at).join(','),building:b.name,title:b.name+' requiere atención',body:b.pending?b.pending+' registros de órdenes pendientes de revisión.':'Se detectó un relé desconectado en una consulta reciente.'})).filter(a=>!this.dismissed.includes(a.id));},dismiss(id){this.dismissed.push(id);},focusBuilding(name){this.q=name;this.tab='todos';this.goTo('edificios');},goTo(id){navigate(this,id);},clearFilters(){this.q='';this.tab='todos';},
 enter(b){location.href='/platform/admin?view=building&tenantId='+encodeURIComponent(b.id);},openSheet(){location.href='/platform/admin?view=new';},async logout(){try{await api('/platform/logout',{});location.href='/login';}catch(e){this.error=e.message;}},
 get offline(){return this.devices.filter(d=>!this.connected(d)||!this.versions[d.device_id]).map(d=>({id:d.device_id,building:d.tenant_name||'Sin asignar',last:d.checked_at?date(d.checked_at):'nunca consultado',rssi:d.rssi==null?'sin medición':d.rssi+' dBm',pinging:this.checking===d.device_id}));},checking:null,
 async retry(d){if(this.checking)return;this.checking=d.id;this.error='';try{const r=await api('/platform/api/relay-inventory/connection',{deviceId:d.id});this.versions[d.id]=r.connection.health?.firmware_revision||'No informada';await this.refresh();this.notify('Consulta completada. No se activó el relé.');}catch(e){this.error=e.message;}this.checking=null;},
 get firmware(){const groups=new Map();for(const d of this.devices){const v=this.versions[d.device_id]||'Sin consultar';groups.set(v,(groups.get(v)||0)+1);}return [...groups].map(([v,n])=>({v,n,cls:v==='Sin consultar'?'bg-gray-300':'bg-material-dark'}));},get fwTotal(){return this.devices.length;},get firmwareLabel(){return this.firmware.map(f=>f.n+' en '+f.v).join(', ');},firmwareWidth(f){return 'width:'+(this.fwTotal?f.n/this.fwTotal*100:0)+'%';},buildingWidth(b){return 'width:'+b.today/this.maxToday*100+'%';},get auditShown(){return this.auditFilter==='mine'?this.audit.filter(a=>a.mine):this.audit;},notify(msg){this.toastMsg=msg;this.toastOn=true;clearTimeout(this._tt);this._tt=setTimeout(()=>{this.toastOn=false;},5000);}
};}
