// Keep browser code as literal source: function.toString() can capture bundler-only helpers.
import { readFileSync, writeFileSync } from 'node:fs';
const source=readFileSync(new URL('../src/html/client-runtime.js',import.meta.url),'utf8').replace(/^\uFEFF/,'').replace('export function clientApp','function clientApp');
writeFileSync(new URL('../src/html/client.js',import.meta.url),'// Generated by tools/build-client.mjs. Edit client-runtime.js instead.\nexport const clientSource = '+JSON.stringify(source)+';\n');
